### ISSUE TITLE
FATAL:  password authentication failed for user \"nextcloud_db_user\"

### ISSUE THREAD

**Issue by ryanbrenden** [nextcloud/vm#2446] opened 2023-03-01 00:57 UTC
### Steps To Reproduce

1. Deploy clean Ubuntu 22.04 VM
2. Go to https://github.com/nextcloud/vm
3. Click on "Code", download as .zip (vm-master.zip)
4. In VM, extract vm-master.zip to ~/vm-master
5. In VM, cd ~/vm-master
6. Run... chmod +x nextcloud_install_production.sh
7. Execute... sudo bash nextcloud_install_production.sh
8. Accept default prompts, e.g. create new user ncadmin, use 2nd disk for "data"
9. Error occurs just after the following installation step...

Creating possible missing Directories
chmod Files and Directories
⣾⣽⣻chown Directories
chmod/chown .htaccess
]
Installing Nextcloud...

10. Two screenshots of errors attached here - key errors state....

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=L5QAaVYGMavmsl*4Z*lxm0OINEE7 --admin-user=ncadmin --admin-pass=nextcloud failed

""message":"Error trying to connect as \"postgres\", assuming database is setup and tables need to be created"

and...

"Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"localhost\" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user \"nextcloud_db_user\"\nconnection to server at \"localhost\"

PostgreSQL username and/or password not valid

<img width="1422" alt="Screenshot 1" src="https://user-images.githubusercontent.com/28836517/222017089-31920670-bd01-4139-a92e-48cf2775e05e.png">
<img width="1422" alt="Screenshot 2" src="https://user-images.githubusercontent.com/28836517/222017108-1a84ea09-5200-4d7e-b6ed-8d07b7953233.png">

### Expected Result

Expectation was the automated vm-master installation script to complete

### Actual Result

Error suggests PostgreSQL username and/or password autogenerated by the script are not valid

### Screenshots, Videos, or Pastebins

<img width="1422" alt="Screenshot 1" src="https://user-images.githubusercontent.com/28836517/222017398-f2512821-8d81-43fd-863d-f200756122a7.png">
<img width="1422" alt="Screenshot 2" src="https://user-images.githubusercontent.com/28836517/222017400-169cbe36-1890-4e58-ba52-623a82bce0b5.png">

### Build Version

25.0.4

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04
4 vCPU
4GB RAM
64GB OS disk, 256GB Data disk

**Comment by enoch85** [comment] 2023-03-01 06:33
Ok, thanks for the report. Nothing changed in the install script since last release, so probably Nextcloud core related (25.0.4). Will have a look during the day.

**Comment by enoch85** [comment] 2023-03-01 13:20
Ok, just tested, and it works with the current scripts:

![image](https://user-images.githubusercontent.com/4511254/222150561-340079dd-6121-444c-975f-def88a0b61af.png)

--> Closing.

**Comment by enoch85** [comment] 2023-04-07 14:38
Finally was able to reproduce the bug now on a customers instance. It's fixed with: https://github.com/nextcloud/vm/pull/2471

Sorry for closing!

**Comment by enoch85** [comment] 2023-04-07 15:14
Fix is now merged, please test.

Closing this issue again.

**Closed by enoch85** 2023-04-07 15:14 UTC
Labels: bug
