### ISSUE TITLE
User ncadmin is hardcoded and causing an error?

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#420] opened 2017-11-29 03:38 UTC
## Steps to reproduce
1. Updated clean Ubuntu Server 16.04
2. Use custom user instead of ncadmin
3. Run script, server reboots for the first time

## Actual behaviour
Error states `id: 'ncadmin': no such user`

## Server configuration
Ubuntu server 16.04 plain vanilla, updated.

**VM version** (master / released version)
Latest as of 20171128

**Updated from an older installed version or fresh install:**
fresh install

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
https://imgur.com/rYgWYCr

**Comment by enoch85** [comment] 2017-11-29 06:19
"It's a feature, not a bug." But yeah, not optimal.

When I have time I'll have a look.

**Comment by thejohnha** [comment] 2017-11-29 14:28
:-)  Thanks Daniel. Not a big deal, but I thought I'd bring it to your attention.

**Comment by enoch85** [comment] 2017-12-10 00:36
It was introduced here: https://github.com/nextcloud/vm/commit/4c03045ad7c0cbb8d96bd03292e54383a9016b2d with intention to better handle users that run with the scripts on a VPS as a pure root user (which isn't optimal). 

I will figure out how we can improve this until next release.

**Comment by enoch85** [comment] 2017-12-10 03:07
The fix is merged. Can you please try again?

Thanks!

**Comment by enoch85** [comment] 2017-12-10 03:21
I'll close this now as I tested myself, but please confirm that it's working for you as well.

**Closed by enoch85** 2017-12-10 03:21 UTC

**Comment by thejohnha** [comment] 2017-12-20 14:03
@enoch85 working well! Thank you so much.  :-)

**Comment by enoch85** [comment] 2017-12-20 14:34
Thank you for confirming! :)
