### ISSUE TITLE
nextcloud talk

### ISSUE THREAD

**Issue by TERABITNET** [nextcloud/vm#2375] opened 2022-08-11 16:04 UTC
### Steps To Reproduce

Error log is
 
Executing: /lib/systemd/systemd-sysv-install enable janus
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻E: The repository 'https://packaging.gitlab.io/janus/jammy jammy Release' does not have a Release file.
]
dpkg-query: no packages found matching nextcloud-spreed-signaling
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻E: The repository 'https://packaging.gitlab.io/janus/jammy jammy Release' does not have a Release file.
]

### Expected Result

I can’t install nextcloud talk. Please how to fix and add trusted repository for HPB

### Actual Result

Executing: /lib/systemd/systemd-sysv-install enable janus
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻E: The repository 'https://packaging.gitlab.io/janus/jammy jammy Release' does not have a Release file.
]
dpkg-query: no packages found matching nextcloud-spreed-signaling
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻E: The repository 'https://packaging.gitlab.io/janus/jammy jammy Release' does not have a Release file.
]

An unexpected error occurred:
Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: talk.priuscenter.mn, retry after 2022-08-13T01:19:17Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Trying to generate certs and validate them with dns method.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for talk.priuscenter.mn
An unexpected error occurred:
Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: talk.priuscenter.mn, retry after 2022-08-13T01:19:17Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

### Build Version

last version

### Environment

By downloading the VM

### Environment Details

[Config when built](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration)
Ubuntu Server 22.04 (minimal) LTS 64-bit
Apache 2.4
PostgreSQL 14
PHP-FPM 8.1
Linux Kernel: 5.15
[Redis Memcache](https://docs.nextcloud.com/server/16/admin_manual/configuration_server/caching_configuration.html#id2) (latest stable version from [PECL](https://pecl.php.net/package/redis))
[PHP-igbinary](https://github.com/igbinary/igbinary) (latest stable version from [PECL](https://pecl.php.net/package/igbinary)
[PHP-smbclient](https://github.com/eduardok/libsmbclient-php) (latest stable version from [PECL](https://pecl.php.net/package/smbclient))
Nextcloud Server [Latest](http://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE)
LDAP (Nextcloud app)
SMB-ready
Collabora Online / Onlyoffice
Nextcloud Talk
DATA disk: 1000 GB
OS disk: 40 GB

**Comment by enoch85** [comment] 2022-08-12 15:54
Duplicate of https://github.com/nextcloud/vm/issues/2371

**Closed by enoch85** 2022-08-12 15:54 UTC
Labels: bug
