### ISSUE TITLE
Disk gets full

### ISSUE THREAD

**Issue by dplx12** [nextcloud/vm#2529] opened 2023-07-27 11:10 UTC
### Steps To Reproduce

After some time the Webserver and othter services stop working. I think the system drive gets full. Aligned the size already, but that happens again after some time. 

### Expected Result

Working Webfrontend

### Actual Result

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

### Additional Context

How can i identify the source of filling the system disk up?

### Build Version

newest

### Environment

By using the scripts

**Comment by enoch85** [comment] 2023-07-27 11:53
This is not a bug. DB grows over time, so does other things in the OS. If it's the DATA drive, then same ting applies there.

For the DATA drive, each time you run an update snapshots are removed if the space is less than 70% left. So, please try to run an update with the built in script. If that doesn't work, enlarge the drive.

**Comment by enoch85** [comment] 2023-07-27 11:53
And also, thanks for reporting! :)

**Comment by tsull360** [comment] 2023-07-28 00:14
I'm experiencing this as well. As a result updates fail midway through the process. The boot drive is sized at 43GB, data drive is 2 TB. 

I've disabled the swap.img file, that helped until I did an update then all space was consumed. Not entirely sure what's chewing up the space though.

**Comment by enoch85** [comment] 2023-07-28 06:38
> I'm experiencing this as well. As a result updates fail midway through the process. The boot drive is sized at 43GB, data drive is 2 TB.
> 
> I've disabled the swap.img file, that helped until I did an update then all space was consumed. Not entirely sure what's chewing up the space though.

For how long did you have the VM?

**Comment by dplx12** [comment] 2023-07-28 07:53
We had it for around one week when the 43 GB System-Drive got full. I already enhanced the capacity to 200 GB then. But now, after 4 more weeks the 200 GB are full again.

**Comment by enoch85** [comment] 2023-07-28 08:09
> We had it for around one week when the 43 GB System-Drive got full. I already enhanced the capacity to 200 GB then. But now, after 4 more weeks the 200 GB are full again.

OK, you can try this and post the result:

https://www.tecmint.com/find-top-large-directories-and-files-sizes-in-linux/

**Comment by dplx12** [comment] 2023-07-28 08:10
Yes, I already did:

![grafik](https://github.com/nextcloud/vm/assets/88666573/987ab104-5808-48dd-bc22-a1302deef940)

**Comment by enoch85** [comment] 2023-07-28 08:28
OK, so some of your docker containers are taking all the space. What are you running?

`docker ps -a`

**Comment by enoch85** [comment] 2023-07-28 08:29
Oh, I can see now that you only checked in `/var` please check in `/` instead.

**Comment by dplx12** [comment] 2023-07-28 08:42
these are the ones:

![grafik](https://github.com/nextcloud/vm/assets/88666573/d6cc69ac-23e1-4e0d-a411-783211606c3b)

Here the check of sizes in /

![grafik](https://github.com/nextcloud/vm/assets/88666573/79e6ecc7-8ca3-4932-a541-17810cb95614)

**Comment by enoch85** [comment] 2023-07-28 09:44
Please uninstall FTS by running the script from `/var/scripts/menu.sh` and choose uninstall.

https://github.com/nextcloud/vm/issues/2528

**Comment by dplx12** [comment] 2023-07-28 10:05
Where is the uninstall-option? there are only options for installing applications.

**Comment by enoch85** [comment] 2023-07-28 11:06
> Where is the uninstall-option? there are only options for installing applications.

Run the script and notice it will ask you to uninstall.

**Comment by tsull360** [comment] 2023-07-28 14:17
My NextCloud deployment now displays a message this message.

![image](https://github.com/nextcloud/vm/assets/19385205/7242775c-4a05-4fb1-89cc-71d06c2df45b)

 Its been online for a few weeks but hasn't had any data loaded while I learn/explore. I'm going to start from scratch at this point.

**Comment by enoch85** [comment] 2023-07-28 15:43
> Sorry, when I run the installer it crashes. May the disk is too full?
> 
> ![grafik](https://user-images.githubusercontent.com/88666573/256831856-05d1e39c-5d9d-4e48-9213-b3bc95df90b6.png)

You have another issue. The uninstaller will remove stuff, not add something new. 

The whole output would be useful.

**Comment by enoch85** [comment] 2023-07-29 07:29
> My NextCloud deployment now displays a message this message.
> 
> ![image](https://user-images.githubusercontent.com/19385205/256846677-7242775c-4a05-4fb1-89cc-71d06c2df45b.png)
> 
> Its been online for a few weeks but hasn't had any data loaded while I learn/explore. I'm going to start from scratch at this point.

Please note that the best way to upgrade the VM is this: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE

**Comment by thatstheplace** [comment] 2023-07-30 14:35
Uninstall of FTS isn't working.

If I try it with the sudo bash /var/scripts/menu.sh it says `Sorry, it's not possible to install FTS anymore since Nextcloud decided to remove support for OpenSearch.     │ 
                     │ Read more in this issue: https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/271`

So I'can't go to reinstall/uninstall options, but OpenSearch Docker Container and FTS Apps are still installed.

**Comment by enoch85** [comment] 2023-07-30 18:34
> Uninstall of FTS isn't working.
> 
> If I try it with the sudo bash /var/scripts/menu.sh it says `Sorry, it's not possible to install FTS anymore since Nextcloud decided to remove support for OpenSearch. │ │ Read more in this issue: https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/271`
> 
> So I can't go to reinstall/uninstall options, but OpenSearch Docker Container and FTS Apps are still installed.

Aah ok, thanks, shoudl be fixed now.

**Closed** 2023-08-02 11:12 UTC
