### ISSUE TITLE
How is the let's encrypt validation done (which challenge)

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#1368] opened 2020-08-13 23:46 UTC
Hi,

how is the let's encrypt validation done, I guess http challenge?
I'm asking because I only want to make nextcloud and especially (!) bitwarden accessible via VPN. That means, the let's encrypt autorenewal won't work because the let's encrypt CA wouldn't be able to do the validation if the services aren't reachable from the internet.

In my case I'm lucky because I use a reverse proxy to publish my stuff to the internet so I could allow access from the internet to something like http://my.domain.com/certvalidation/* but deny access to https://my.domain.com where nextcloud lives.

For that to configure, I obviously would need to know what URL is used, I hope there is a subdirectory for the validation which I could use to filter the requests? :-)

Thanks!

PS: I'm approaching the goal of having my appliance up and running like I want it, I'll create the new VMs with the recommended VMware settings like I promised in an earlier issue when I'm done with that.

**Comment by enoch85** [comment] 2020-08-14 07:29
LE is done with the certbot snap. You can read the code here:

Cerbot: https://github.com/nextcloud/vm/blob/master/lib.sh#L510-L524
Validation: https://github.com/nextcloud/vm/blob/master/lib.sh#L526-L590

Basically, we start with standalone which requires http, and if that doesn't work we try DNS since that's always working - even behind strict firewalls. 

The downside with DNS though is that it doesn't autorenew, but if you put your TLS on a proxy, then problem is solved anyway.

**Comment by mamama1** [comment] 2020-08-14 19:07
Thanks, i published the following URLs through my reverse proxy and neither nextcloud nor bitwarden are accessible now via the internet but let's encrypt verification works flawlessly. Just like I wanted it (i wanted to make them accessible solely via VPN) :-) Maybe that's something for the documentation?

https://bitwarden.mydomain.com/.well-known/acme-challenge/
http://bitwarden.mydomain.com/.well-known/acme-challenge/

https://nextcloud.mydomain.com/.well-known/acme-challenge/
http://nextcloud.mydomain.com/.well-known/acme-challenge/

**Comment by enoch85** [comment] 2020-08-14 20:29
Sure, you can write the docs here and I'll copy paste them to the real docs. :)

Thanks!

**Comment by enoch85** [comment] 2020-08-14 20:29
Issue solved --> closing.

**Closed by enoch85** 2020-08-14 20:29 UTC

**Comment by bobdig** [comment] 2020-09-06 07:08
> The downside with DNS though is that it doesn't autorenew,

@enoch85 Is there a way around this problem? Had this happened to me too.

**Comment by enoch85** [comment] 2020-09-06 10:43
Yes there is: https://github.com/nextcloud/vm/issues/734

**Comment by bobdig** [comment] 2020-09-06 10:51
@enoch85 Because of some (my) noobness, do you consider adding this script to your setup? Also I wonder why certbot doesn't auto renew. I have created the inifile etc. I really don't get it, why it is not auto renewing. Is this specific to your setup? 
TIA

**Comment by enoch85** [comment] 2020-09-06 12:15
>  do you consider adding this script to your setup?

Sure, that's why the issue is there. :+1: But it requires time - that I don't have right now.

> why it is not auto renewing

That's how the DNS validation works, every 3 months you have to manually set the DNS records for it to work. For it to autorenew, you need to use some other validation method, but that also means that you need to open the correct ports and let them stay open - so in your case I guess it's a firewall thing that needs to be fixed.

**Comment by bobdig** [comment] 2020-09-06 12:22
@enoch85 I mean I don't get, why certbot is not auto renewing itself like it does with the normal challenge. 
I mean, if you have prepared that inifile like I have and don't move it, there is no reason why it is not auto renewing.

My server is behind a vpn, so no need for "fixing" the ports I guess. :)

**Comment by enoch85** [comment] 2020-09-06 12:31
Like I said, every three months the TXT records needs updating since it's changing the values. How did you expect certbot to take care of that? :)

It's possible with Cloudflare, their API, and some scripting - as in the issue I linked. But if you're bound to use the DNS vakidation without using Cloudflare - you're also bound to update the DNS records manually

**Comment by enoch85** [comment] 2020-09-06 12:32
The closest to automation you can get with DNS in tje current implementation, is running the LE script every three months.
