### ISSUE TITLE
Unable to restore database

### ISSUE THREAD

**Issue by gpz1100** [nextcloud/vm#1795] opened 2021-02-04 01:55 UTC
## Steps to reproduce
1. Successful backup of database using instructions  https://docs.nextcloud.com/server/20/admin_manual/maintenance/backup.html?highlight=database#postgresql

PGPASSWORD="{PASSWORD_FROM_config.php}" pg_dump nextcloud_db -h localhost -U ncadmin -f nextcloud-sqlbkp_`date +"%Y%m%d"`.bak

2. Attempt to restore database  https://docs.nextcloud.com/server/20/admin_manual/maintenance/restore.html#postgresql

drop database
PGPASSWORD="{PASSWORD_FROM_config.php}" psql -h localhost -U ncadmin -d template1 -c "DROP DATABASE \"nextcloud_db\";"
completes successfully

create new database
PGPASSWORD="{PASSWORD_FROM_config.php}" psql -h localhost -U ncadmin -d template1 -c "CREATE DATABASE \"nextcloud_db\";"
ERROR:  permission denied to create database

## Expected behaviour
Database should get recreated as specified in the docs

## Actual behaviour
Fails to recreate database

## Server configuration

**Nextcloud server version:** (see your admin page)
20.0.6.1

**Server OS** (Ubuntu server is default)
ubuntu 20.04.2 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)
scripted from installer in vm

## Network
**Do you use DHCP?**
N/A

**Is port 80 and/or 443 open?**
N/A

################  Please use https://0bin.net for long error messages or logs. Thanks! ################
2021-02-04 01:52:14.122 UTC [146440] ncadmin@template1 ERROR:  permission denied to create database
2021-02-04 01:52:14.122 UTC [146440] ncadmin@template1 STATEMENT:  CREATE DATABASE "nextcloud_db";

#### Log file : /var/log/postgresql/postgresql-12-main.log
```


Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by gpz1100** [comment] 2021-02-04 03:39
Digging further into the installation docs (https://docs.nextcloud.com/server/20/admin_manual/configuration_database/linux_database_configuration.html), near the bottom they explain how to create the user and database.

> To start the postgres command line mode use:

`psql -hlocalhost -Upostgres`

>Then a postgres=# prompt will appear. Now enter the following lines and confirm them with the enter key:

```
CREATE USER username WITH PASSWORD 'password';
CREATE DATABASE nextcloud TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE nextcloud OWNER TO username;
GRANT ALL PRIVILEGES ON DATABASE nextcloud TO username;
```
The last line is of interest.  It assigns full privileges to user {username}. 

Vm installation script nextcloud_install_production.sh, https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh , lines 339 and 340 perform a similar function.

 
``````` 
cd /tmp
sudo -u postgres psql <<END
CREATE USER $NCUSER WITH PASSWORD '$PGDB_PASS';
CREATE DATABASE nextcloud_db WITH OWNER $NCUSER TEMPLATE template0 ENCODING 'UTF8';
END
print_text_in_color "$ICyan" "PostgreSQL password: $PGDB_PASS"
systemctl restart postgresql.service
```````

However, all privileges are not assigned, resulting in the in ability to recreate the database, and subsequently failure of the restore process.  How can this be resolved?

**Comment by enoch85** [comment] 2021-02-04 05:35
If you create a database with the OWNER command you don't need to GRANT as the OWNER already is the correct user.

**Comment by gpz1100** [comment] 2021-02-04 06:49
If such is the case why is the recreation of the database failing until CREATEDB permission is added to ncadmin?

**Comment by enoch85** [comment] 2021-02-04 19:36
When you create the database you don't need a GRANT argument.

What you need is to look at your restore procedure, or the specific command. Just using the install script to setup a new instance is the easiest way. Then just restore whatever you want to that newly setup VM/Server.

Closing since this is not a bug, rather a support ticket.

**Closed by enoch85** 2021-02-04 19:36 UTC
Labels: Support
