### ISSUE TITLE
Install Script and Data Storage

### ISSUE THREAD

**Issue by dereddick** [nextcloud/vm#1342] opened 2020-08-06 02:45 UTC
## Steps to reproduce
1. Fresh install of Ubuntu on Upcloud with secondary storage added
2. Created ZFS pool (ncdata) mounted to `/mnt/ncdata`
3. Run script

## Expected behaviour
Script when ask to configure disks should allow data loction to be selected .

## Actual behaviour
Script says needs a second disk and it be mounted with ZFS. I already have a second disk mounted and partitioned with ZFS to `/mnt/ncdata`. I also tried with the disk having no partition and another try with the disk having an ext4 partition with same results of the script not being able to locate the disk.

## Server configuration

**Nextcloud server version:** Not installed yet but script from master

**Server OS** Ubuntu 20.04

**How did you install the VM?** Scripted from Master

## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes

**Comment by enoch85** [comment] 2020-08-06 07:13
Hi,

Thanks for posting!

The second disk should be unformated and unmounted in thr guest system.

Please do that and try again.

**Comment by enoch85** [comment] 2020-08-06 14:34
Closing this since it's not a bug.

**Comment by dereddick** [comment] 2020-08-06 16:46
I mentioned in the original report I tried no partition on the second disk with the same result, but I just tried again. This is my `lblk` showing the secondary disk `vdb` has no partition.

> NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
>vda    252:0    0   25G  0 disk 
>└─vda1 252:1    0   25G  0 part /
>vdb    252:16   0  100G  0 disk

**Comment by enoch85** [comment] 2020-08-06 16:48
Thanks! Which hypervisor are you running?

**Comment by enoch85** [comment] 2020-08-06 16:50
I don't have a Red Hat server available, but it should be supported: https://github.com/nextcloud/vm/blob/master/static/format-sdb.sh#L46

**Comment by dereddick** [comment] 2020-08-06 16:58
This is a cloud instance on Upcloud and is virtualized with KVM.

The script you recommended is still saying I didn't add a second disk.

**Comment by dereddick** [comment] 2020-08-06 16:59
This is my `hostnamectl`

>   Static hostname: ****
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 009ea2d7d1134529b0f1e775a8a1c60a
           Boot ID: 3061fe72b3874ae78bc41db6c2aaf2b5
    Virtualization: kvm
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-29-generic
      Architecture: x86-64

**Comment by enoch85** [comment] 2020-08-06 19:32
Please post the output of:

1. `fdisk -l`
2. `ls -l /mnt/ncdata`
3. `df -h`

Thanks!

**Comment by dereddick** [comment] 2020-08-06 20:17
1. `fdisk -l`

> Disk /dev/vda: 25 GiB, 26843545600 bytes, 52428800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xdbbe49d8
>
>Device     Boot Start      End  Sectors Size Id Type
/dev/vda1        2048 52428799 52426752  25G 83 Linux
>
>Disk /dev/vdb: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: B19A514E-FE9A-4F4C-A5BE-C5B290BB27F0

2. `ls -l /mnt/ncdata` 

>total 0

3. `df -h`

>Filesystem      Size  Used Avail Use% Mounted on
udev            449M     0  449M   0% /dev
tmpfs            99M  728K   98M   1% /run
/dev/vda1        25G  3.0G   21G  13% /
tmpfs           491M  8.0K  491M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           491M     0  491M   0% /sys/fs/cgroup
tmpfs            99M     0   99M   0% /run/user/0

**Comment by enoch85** [comment] 2020-08-06 20:35
OK, so that seems correct.

And what's the exact error you are getting? Screenshots please. 

Also download the script, run it with `sudo bash -x` and post the output in a pastebin.

Thanks!

**Comment by dereddick** [comment] 2020-08-06 21:04
The terminal output: https://pastebin.com/35crPW96
Screenshots: https://imgur.com/a/2GvIfed

**Comment by enoch85** [comment] 2020-08-06 21:41
OK, so the CLI output tells me you are using UpCloud, is that correct?

The error in that case is that UpCloud isn't listed as a `SYSVENDOR` which means the script falls back to the standard `sdb`.

To solve it you would have to add UpCloud as a `SYSVENDOR`. Easily done, question is, do they only use `vdX` or does their disk list as `sdb`, or anything else as well?

I can make a PR if you find out that info, like contacting them and ask.

**Comment by enoch85** [comment] 2020-08-06 21:43
> This is a cloud instance on Upcloud and is virtualized with KVM. 

Duuh, saw this now. 

So, is it possible to run non-KVM as well with them?

**Comment by enoch85** [comment] 2020-08-06 22:02
OK, so I created an account and it turns out you can choose between 3 storage layouts.

The default gives you `vdX` and the other two gives you `sdX`.

Can you please redeploy another server with ISCSI or IDE instead just to test if the script works then?

**Comment by dereddick** [comment] 2020-08-06 22:02
From everything, I have found in their materials all of the VM's based on their templates use KVM. They do have instructions on a way to import a VMware image to run on the VPS so the drives may be mounted differently but will still be running with KVM.

**Comment by dereddick** [comment] 2020-08-06 22:41
The new format script pull request works. However, the nextcloud install script still gives the error where it says I didn't add a second disk but the command line after clicking past the error no longer says `cannot import 'ncdata': no such pool available`. Would the new pull request when approved just need me to pull a new copy of the nextcloud install script?

**Comment by enoch85** [comment] 2020-08-06 22:43
OK, great! Then I'll merge the PR. 

Please give the install script another try in 5 minutes and report back.

Thanks.

**Closed** 2020-08-06 22:43 UTC
Labels: enhancement

**Comment by enoch85** [comment] 2020-08-06 23:07
@dereddick So did it work? :)

**Comment by dereddick** [comment] 2020-08-06 23:44
I tried a fresh VM with fresh secondary storage to make sure everything works as intended but I can't get it to work.

>no pools available
/dev/vdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
ncdata /mnt/ncdata zfs rw,noatime,xattr,noacl 0 0
  vdb      99.5G   984K  99.5G        -         -     0%  0.00%      -  ONLINE  
/dev/fd/63: line 719: partprobe: command not found
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
partprobe -s failed
sudo: php: command not found

If I then try and run the command again it says the pool agready exists so I'm not sure if it is working or not.

>/dev/vdb is a member of a ZFS pool and needs to be removed from any zpool before you can run this script.

**Comment by dereddick** [comment] 2020-08-07 00:21
I've tested with multiple quick instances with the same result. I am only creating a VM with an extra drive, creating a secondary user with sudo access, switching to that user, cloning the repo, and running the same script. I'm not sure if this is a different problem that needs a new issue created but it is still related to data storage with the install script on an UpCloud VPS.

**Comment by enoch85** [comment] 2020-08-07 08:34
@dereddick Strange! I tested to install on multiple instances yesterday and it worked for me.

The **only** thing you should do after the VPS is setup is:

1. `wget https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh`
2. `bash nextcloud_install_production.sh`
3. Follow the instructions.

**Comment by enoch85** [comment] 2020-08-07 09:10
Sorry, my bad. `parted` was not installed in UpCloud. It's fixed now.

**Comment by dereddick** [comment] 2020-08-07 18:27
Great, after installing the extra package, the install worked as intended.

**Comment by enoch85** [comment] 2020-08-07 18:40
Great! Feel free to donate. :)
