### ISSUE TITLE
Error when attempting to update from 22.2.2 to 22.2.3

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#2177] opened 2022-01-04 23:29 UTC
### Steps To Reproduce

sudo bash /var/scripts/menu.sh to start minor update

### Expected Result

Update to succeed. 

### Actual Result

Update fails with the following error. 

### Screenshots, Videos, or Pastebins

<img width="1003" alt="2022-01-04_17-57-28" src="https://user-images.githubusercontent.com/8496835/148137667-304b3f74-38e1-4121-ab3c-fc7d82f98ca3.png">

### Build Version

22.2.2

### Environment

By using the scripts, By downloading the VM

### Environment Details

Using hanssonit Hyper-V

**Comment by szaimen** [comment] 2022-01-05 01:17
Duplicate of https://github.com/nextcloud/groupfolders/issues/1854

**Closed by szaimen** 2022-01-05 01:17 UTC
Labels: bug
