### ISSUE TITLE
Installation script errors

### ISSUE THREAD

**Issue by h45h3ncryp73d** [nextcloud/vm#1703] opened 2020-11-30 16:58 UTC
## Steps to reproduce
1. Install Ubuntu LTS 20.04.1
2. Run sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"

## Expected behaviour
Installation should succeed.

## Actual behaviour
Installation fails with errors being present from the installation start until finally fatal error occurred.

## Server configuration
2 vCPU / 4GB ECC RAM / 160GB + 1TB

**Nextcloud server version:**
Latest should be installed ...

**Server OS**
Ubuntu LTS 20.04.1

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from master.

## Network
**Do you use DHCP?**
No.

**Is port 80 and/or 443 open?**
Yes.

## Logs / Screenshots
N/A

#### Log file (/var/log/nextcloud/nextcloud.log)
Empty.

#### Installation log (command output)
https://0bin.net/paste/GpmIGbK5#dhRICFiveO2M1zOUc1SO01HQnVzjwPwm-0pjVLQsBCH

#### Screenshoots
N/A

**Comment by enoch85** [comment] 2020-11-30 18:52
Hi, it works here. The message you are getting seems to indicate that apache can't be installed, but the command itself are correct - so it might just be a temporary error.

Since this is not a bug, I'm closing.

**Closed by enoch85** 2020-11-30 18:52 UTC
