### ISSUE TITLE
HTTP to HTTPS redirect isn't working & SSLLabs test HTTP and Redirect errors

### ISSUE THREAD

**Issue by virtuallysurreal** [nextcloud/vm#182] opened 2017-03-31 18:16 UTC
## Steps to reproduce
1. Fresh setup of 11.0.2.7 16.0.4 Ubuntu 20GB VM in VMware Workstation Pro 12.5.5 build-5234757 on Windows 10 Home 64-bit host, fresh installed less than 4 weeks ago, up to date with all patches.
2. Do you run this on a remote VPS - No
3. Static IP address setup as a DHCP Reservation in the router and displayed correctly on screen when running configuration script and saved to /etc/network/interfaces
4. Keyboard > 	Generic 104-key PC [NOT INTL] > English (US) > English (US) > The default > No compose key
5. Used custom domain and LetsEncrypt certificate. 
6. No Apps installed
7. Postfix configuration with Internet Site
8. TimeZone > US > Central
9. Set ncadmin and Nextcloud passwords
10. Saw it set hostname to what I set before for LetsEncrypt and rebooted.
11. Saved VMware snapshots immediately after the initial setup script finished running, and occasionally up through my final customization and setup.

## Expected behaviour
When trying to go to http://custom.domain.com, it should redirect to https://custom.domain.com instead of timing out.
SSLLabs should not show HTTP errors and Redirect errors

## Actual behaviour
Tried to load http://custom.domain.com, and it times out.
Ran a test at https://www.ssllabs.com/ssltest/index.html, and the following errors come up:
HTTP request to this server failed, see below for details.
HTTP status code 	Request failed (Too many Redirection)
HTTP server signature 	Apache/2.4.18 (Ubuntu)
Even after reverting back to the VMware snapshot immediately after initial config script finished, the same errors appear.

Upon finishing configuration, there were 3 virtual hosts in Apache.
My previous operational install of v11.0.0.10 has 5 virtual hosts in Apache, which did not exhibit these issues.

## Server configuration

**Server version:** (see your admin page)
11.0.2 (stable)

**VM version** (master / released version)
Ubuntu 16.04: Pre-installed Nextcloud (PHP 7) 20GB
Last updated: 2017-02-27. Version: 11.0.2
in VMware Workstation Pro 12.5.5 build-5234757 

**Updated from an older installed version or fresh install:**
Fresh install

## Network
**Do you use DHCP?**
DHCP Reservation on router with correct IP showing during initial setup that was saved to /etc/network/interfaces

**Is port 80 and/or 443 open?**
443 is open and forwarded in router. Since ownCloud, I've not needed to specifically forwarded 80.

#### Log file (/var/ncdata/nextcloud.log)
```
{"reqId":"zJdXeKf4FEL81mMhoTXX","remoteAddr":"71.6.146.185","app":"core","message":"Trusted domain error. \"71.6.146.185\" tried to access using \"72.213.xxx.xxx\" as host.","level":2,"time":"2017-03-31T07:53:14-05:00","method":"GET","url":"\/","user":"--","version":"11.0.2.7"}
```

#### Installation log (command output)
```
Please direct me how to "Insert the CLI output here" and I'll be happy to do so.
```

**Comment by enoch85** [comment] 2017-03-31 19:08
Thanks for a detailed report!

> Postfix configuration with Internet Site

This could be it. I never tested Posix in combination with Let's Encrypt. 

For the redirect part there is a redirect in the conf that is activated when running the SSL script (Let's Encrypt). Could you please post the output of `cat /etc/apache2/sites-enabled` and also `cat /etc/hostname`? Thanks!

**Comment by virtuallysurreal** [comment] 2017-03-31 19:42
I've used the same Postfix setting with internet site since an older version of ownCloud, but as I mentioned I'm not experienced with Linux/Ubuntu and have relied on the prebuilt VMs instead of going through a full config from scratch.

I ran those commands as requested on the problematic install:

ncadmin@orders:~$ cat /etc/apache2/sites-enabled
cat: /etc/apache2/sites-enabled: Is a directory
ncadmin@orders:~$ cat /etc/hostname
my.custom.domain (scrubbed, but if necessary I can message actual domain)
ncadmin@orders:~$

The older VM is still on another computer if any information is requested from that to compare.

**Comment by enoch85** [comment] 2017-03-31 19:57
Sorry, wrong command. Do this instead: `ls -l /etc/apache2/sites-enabled`

**Comment by enoch85** [comment] 2017-03-31 20:17
Also, what happens if you open port 80 in the router. Shouldn't have any effect but still, just to rule out the obvious.

**Comment by virtuallysurreal** [comment] 2017-03-31 20:31
`ncadmin@orders:~$ ls -l /etc/apache2/sites-enabled`
`total 0`
`lrwxrwxrwx 1 root root 51 Mar 31 05:04 my.custom.domain.conf -> ../sites-available/my.custom.domain.conf`
`lrwxrwxrwx 1 root root 51 Mar 31 12:12 webmin.1490980374.conf -> /etc/apache2/sites-available/webmin.1490980374.conf`

Correct, opening and forwarding port 80 didn't change anything concerning HTTP not redirecting to HTTPS.

With what I could compare between the two installs concerning my limited knowledge, what stood out the most to me was 5 virtual hosts with different settings setup with 11.0.0.10 and only 3 virtual hosts with 11.0.2.7, if there might be anything there.

**Comment by enoch85** [comment] 2017-03-31 20:41
OK, why do you have a configuration for Webmin there? Something you made? How does it look inside?

Also, how does your domain config look like inside?

**Comment by virtuallysurreal** [comment] 2017-03-31 20:52
In general, I've used Webmin to look at and change some settings, edit files. Why there is a config file listed there concerning webmin, I cannot say.

In fact, I try to find it inside the file manager, and it's not there. Nothing shows up when I try to open it in nano in console.

The domain config:

> <VirtualHost *:80>
    ServerName my.custom.domain
    Redirect / https://my.custom.domain
</VirtualHost>

<VirtualHost *:443>

    Header add Strict-Transport-Security: "max-age=15768000;includeSubdomains"
SSLEngine on

### YOUR SERVER ADDRESS ###

ServerName my.custom.domain

### SETTINGS ###

DocumentRoot /var/www/nextcloud

    <Directory /var/www/nextcloud>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    Satisfy Any
    </Directory>

    <IfModule mod_dav.c>
    Dav off
    </IfModule>

    SetEnv HOME /var/www/nextcloud
    SetEnv HTTP_HOME /var/www/nextcloud


### LOCATION OF CERT FILES ###

    SSLCertificateChainFile /etc/letsencrypt/live/my.custom.domain/chain.pem
SSLCertificateFile /etc/letsencrypt/live/my.custom.domain/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/my.custom.domain/privkey.pem
SSLProtocol +TLSv1.2

</VirtualHost>

>

**Comment by enoch85** [comment] 2017-03-31 20:57
As you can see in the default config (created when you run the SSL script) it's pre-configured to redirect all http traffic to https.

Since this is not a bug, and everything is as it should VM wise, I'm not sure I can help you here.  It's hard for me to know what you have changed in Webmin. According to what you have given me, it seems like the VM works out of the box.

My suggestion though would be to do: `a2dissite webmin.1490980374.conf && service apache2 reload` as most likley you changed something with Webmin that caused this error.

Please let me know if it worked.

**Comment by virtuallysurreal** [comment] 2017-03-31 21:20
I did try to look into things myself prior to posting here, and didn't restore back to a previous snapshot before running those commands and providing the results.

Going back to the first snapshot I took after the initial setup script ran, where the problem still exists, there is no webmin.1490980374.conf listing, so let me post the information from that point to see if it helps at all:

```
ncadmin@orders:~$ ls -l /etc/apache2/sites-enabled
total 0
lrwxrwxrwx 1 root root 51 Mar 31 05:04 my.custom.domain.conf -> ../sites-available/my.custom.domain.conf
```

Definitely no listing of webmin.*.conf there with that snapshot.

```
<VirtualHost *:80>
    ServerName my.custom.domain
    Redirect / https://my.custom.domain
</VirtualHost>

<VirtualHost *:443>

    Header add Strict-Transport-Security: "max-age=15768000;includeSubdomains"
    SSLEngine on

### YOUR SERVER ADDRESS ###

    ServerAdmin admin@my.custom.domain
    ServerName my.custom.domain

### SETTINGS ###

    DocumentRoot /var/www/nextcloud


```

**Comment by virtuallysurreal** [comment] 2017-03-31 21:54
If there's no potential cause from that last info, or any other obvious places the cause could be stemming from, I'll try a fresh reload again tonight and try to pay closer attention to look for any potential errors or messages during the initial settings script. If it still has the same problem, I'll post back before changing any settings/configuration.

**Comment by enoch85** [comment] 2017-03-31 22:04
Send me an email at: daniel at techandme.se

**Comment by enoch85** [comment] 2017-04-03 11:18
This is fixed in the increased code quailty branch

**Closed by enoch85** 2017-04-03 11:18 UTC
