### ISSUE TITLE
Appliance (Nextcloud-VM.ova) fails to setup

### ISSUE THREAD

**Issue by jkdale** [nextcloud/vm#1674] opened 2020-11-13 17:51 UTC
## Steps to reproduce
1. Download Current VM
2. Follow instructions taking all defaults

## Expected behaviour
New to the product, I wanted to try out the appliance. I downloaded and spun up the OVA in VMWARE16 Pro. Answering the default answers, it eventually landed on this error and failed to complete the install. I am not sure what to expect, but I don't believe this is right.

## Actual behaviour
It threw an error told me to report it here

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
https://download.nextcloud.com/vm/Nextcloud-VM.ova

## Network
**Do you use DHCP?**
YEs
**Is port 80 and/or 443 open?**
Don't know yet
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Stat: cannot stat '/mnt/ncdata/*': No such file or directory
```

#### Screenshots

https://imgur.com/a/4fbaA1c

**Comment by szaimen** [comment] 2020-11-13 19:21
I've got the same error while running the install script

**Comment by enoch85** [comment] 2020-11-13 19:32
> It threw an error told me to report it here

What was the error?

Also, you're using the "wrong" VM. 

Please try this one: https://github.com/nextcloud/vm/releases/tag/20.0.1 and report back

**Comment by szaimen** [comment] 2020-11-13 20:18
@enoch85 I've just run the startup script and /mnt/ncdata was chown to root:root, hence the nextcloud installation failed.
Maybe this appeared because I've chosen 1 Disk during the setup?

**Comment by mcbuble** [comment] 2020-11-13 23:34
Have the screen shoot error tuning the on vmrsxi 6.7![image](https://user-images.githubusercontent.com/34319024/99130621-cf76bc80-264b-11eb-8b7b-ec3207a2f42d.jpeg)

**Comment by jdb1941** [comment] 2020-11-14 01:21
I'm getting the same error when trying to install on esxi 6.7. When scrolling up in the text of the install, it seems that zfs cannot mount the pool 'ncdata'.

`no pools available
/dev/sdb: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sdb: 8 bytes were erased at offset 0x1d1c1115e00 (gpt): 45 46 49 20 50 41 52 54
/dev/sdb: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
ncdata /mnt/ncdata zfs rw,noatime,xattr,noacl 0 0
dpkg-query: no packages found matching zfs-auto-snapshot
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  zfs-auto-snapshot
0 upgraded, 1 newly installed, 0 to remove and 76 not upgraded.
Need to get 8,652 B of archives.
After this operation, 42.0 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 zfs-auto-snapshot all 1.2.4-2 [8,652 B]
Fetched 8,652 B in 0s (41.9 kB/s)
Selecting previously unselected package zfs-auto-snapshot.
(Reading database ... 113232 files and directories currently installed.)
Preparing to unpack .../zfs-auto-snapshot_1.2.4-2_all.deb ...
Unpacking zfs-auto-snapshot (1.2.4-2) ...
Setting up zfs-auto-snapshot (1.2.4-2) ...
Processing triggers for man-db (2.9.1-1) ...
  sdb      1.81T  1020K  1.81T        -         -     0%  0.00%      -  ONLINE
/dev/sda: gpt partitions 1 2 3
/dev/sdb: gpt partitions 1 9
/dev/mapper/ubuntu--vg-ubuntu--lv: loop partitions 1
_**cannot import 'ncdata': no such pool available**_
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the er
**_zpool import -d /dev/disk/by-uuid/ ncdata failed_**
sudo: php: command not found
/var/scripts/change-to-zfs-mount-generator.sh: line 16: /var/scripts/fetch_lib.sh: No such file or directory
cannot import 'ncdata': no such pool available
Synchronizing state of zfs-mount.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable zfs-mount
Removed /etc/systemd/system/zfs.target.wants/zfs-mount.service.
Synchronizing state of zfs-zed.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable zfs-zed
Starting zfs-zed...
**_cannot open 'ncdata': dataset does not exist_**`

**Comment by enoch85** [comment] 2020-11-14 01:58
Actually, this is the fix: https://github.com/nextcloud/vm/commit/27e6badcf122ae400acd1c9c44dd573b0ff908d4

Please try again.

**Comment by enoch85** [comment] 2020-11-14 02:02
Yup, just tested. It works!

**Closed by enoch85** 2020-11-14 02:02 UTC

**Comment by enoch85** [comment] 2020-11-14 18:03
It's confirmed to be working by another user as well: https://github.com/nextcloud/vm/issues/1672
