### ISSUE TITLE
An error occurs when you try to update.

### ISSUE THREAD

**Issue by im-evko** [nextcloud/vm#2376] opened 2022-08-14 19:43 UTC
### Steps To Reproduce

1. When trying to update an older version of nexcloud-vm via /var/scripts/update.sh minor an error occurs
 " Your .ocdata are missing in the Nextcloud data folder. This probably means that you failed to mount the second drive, or that it failed to import during│ boot of the system.  
We can't continue without it, so please shutdown the machine and double check that the second disk is correctly mounted in your hypervisor/server then try again.   If you need support, feel free to contact us here: https://www.hanssonit.se/#contact " 

### Expected Result

Prior to that, I updated this setup from version 20 and everything was fine.

### Actual Result

 " Your .ocdata are missing in the Nextcloud data folder. This probably means that you failed to mount the second drive, or that it failed to import during  boot of the system.  
We can't continue without it, so please shutdown the machine and double check that the second disk is correctly mounted in your hypervisor/server then try again.   If you need support, feel free to contact us here: https://www.hanssonit.se/#contact " 

### Additional Context

In fact, the ".ocdata" file is present in the folder and has not been moved anywhere. 

### Build Version

Nextcloud HanssonIT VM (23.0.4)

### Environment

By using the scripts

**Comment by enoch85** [comment] 2022-08-14 21:14
Thanks for posting!

Sorry, but I can't reproduce this. Usually, missing `.ocdata` means that your second drive is missing, or failed to import. 

You also mention that you did an update on your own, are you sure the path is correct in `config.php`?

**Comment by im-evko** [comment] 2022-08-15 05:59
I deployed this machine with your script and I have done all upgrades since version 20 only as specified in your instructions. It always worked fine, but the last time I tried it, there was an error. I didn't change the configuration files manually, everything that was changed during the upgrade was changed solely by your script. After the error, I also compared all the configuration files with the files I have from the backup. All configuration files and the .ocdata file are also in place and identical except for the different versions. I also have all disks mounted as the installation continues to work fine, but cannot update with the script. I have not done anything manually without the script. 
![espro_2022-08-15_08-56-26](https://user-images.githubusercontent.com/37828025/184583976-a3b0a8f4-1722-430a-9eb3-030939494a9e.png)
![espro_2022-08-15_08-58-31](https://user-images.githubusercontent.com/37828025/184584030-fed23686-5fa5-43c5-bf62-58eb2fe8a9da.png)

**Comment by enoch85** [comment] 2022-08-15 19:42
The `/updater-xxxx` tells me you didn't use the script for updating all the times. We don't produce that folder in the VM scripts.

Other than that, I can't reproduce this. My own installation has been running for 6-7 years, and upgraded with the script. What I produce, I use myself. We don't touch the datadir *at all* during upgrades or any other case for that matter, except maybe setting correct permissions.

This is a support issue, please consider getting support in our shop.

**Comment by im-evko** [comment] 2022-08-15 20:39
In fact, I already updated it myself manually, it's not a problem for me, I was just very surprised that the script gives error about missing .ocdata file, without which Nextcloud just does not work and decided to tell you, because I saw "check if .ocdata exists (#2350)" in the last changes of <lib.sh>. And because before I updated everything with the script and everything worked fine, and then suddenly it stopped because of this check I wrote to you.

**Comment by enoch85** [comment] 2022-08-16 11:02
OK, it's super odd. As I can't reproduce this I have to close it. If someone else shows up with the same error, I'll investigate further.

Thanks for letting us know!

**Closed by enoch85** 2022-08-16 11:02 UTC
Labels: Support
