### ISSUE TITLE
{startup_configuration} failed to download. whay !!!

### ISSUE THREAD

**Issue by lizhihengtt** [nextcloud/vm#1770] opened 2021-01-14 17:12 UTC
{startup_configuration} failed to download. whay !!!
There is no problem with my network
The latest vm.OVA
![image](https://user-images.githubusercontent.com/27955363/104624594-bb444f80-56ce-11eb-8e95-36897dd38692.png)

**Comment by enoch85** [comment] 2021-01-14 18:43
Hi,

It might be a temporary glitch. Just try again and see if it works. Sometimes Github have issues, sometimes your ISP have issues. Script wise though there's nothing wrong. It's doing exactly what it's intended to - warning you and aborting if there's no success.

**Comment by lizhihengtt** [comment] 2021-01-15 04:30
> 你好
> 
> 这可能是暂时的故障。请再试一次，看看是否可行。有时Github遇到问题，有时您的ISP遇到问题。脚本明智，但没有错。它正按照预期的目的执行-警告您，如果没有成功，则中止。

Restart the script but did not succeed.How to solve the problem

**Comment by szaimen** [comment] 2021-01-15 11:38
@lizhihengtt please read this:
https://github.com/nextcloud/vm/blob/ff0da09870627050a2a286a7f6ceeffb09b08da5/nextcloud-startup-script.sh#L205-L212

**Comment by enoch85** [comment] 2021-01-16 21:55
Just installed 3 Nextcloud servers with the scripts, no issues. 

This is not a bug --> closing.

**Closed by enoch85** 2021-01-16 21:55 UTC
