### ISSUE TITLE
Again, no more apps after major update

### ISSUE THREAD

**Issue by jalabaya** [nextcloud/vm#2207] opened 2022-01-30 14:17 UTC
### Steps To Reproduce

- Script executes major update.
- Most apps are gone.
- See https://github.com/nextcloud/vm/issues/2109

### Expected Result

- Script executes major update.
- NC keeps humming as before.

### Actual Result

Apps unusable.
See https://github.com/nextcloud/vm/issues/2109

### Build Version

23.0.1

### Environment

By using the scripts

### Environment Details

This is related to:
https://github.com/nextcloud/vm/issues/2109

The exact same thing happened again after the recent major update.

Again, I had problems getting the apps from the appstore.

Again, I ran the update script manually. There I spotted this:

`Latest version is: 23.0.1. Current version is: 23.0.1.                                                              │ 
               │                                                                                                                     │ 
               │ ||| UPGRADE SUCCESS! |||                                                                                            │ 
               │                                                                                                                     │ 
               │ If you notice that some apps are disabled, it's because they are not compatible with the new Nextcloud version.     │ 
               │ To recover your old apps, please check /mnt/NCBACKUP/apps and copy them to /var/www/nextcloud/apps manually.        │ 
               │                                                                                                                     │ 
               │ Thank you for using T&M Hansson IT's updater!                                                                       │ 
               │                                                                                                                     │ 
               │                                                      
`

So, I copied the apps over, as described. But now on the Apps screen, those apps are disabled. When I try to enable them, there is this error message:

`App "contacts" cannot be installed because appinfo file cannot be read.` The same message for different apps.

So, contrary to the last major update, were getting NC back on track was just slow and took a morning, this time I am left with an unusable system. 

Any advice would be appreciated.

**Comment by enoch85** [comment] 2022-01-30 16:05
Hi,

Thanks for posting!

Nextcloud will disable apps that aren't compatible with your version, hence if updating to a new major version, some apps aren't always compatible. We put a check in place just to protect from anything bad happening to the update itself, hence the apps are disabled.

You can visit the app store and enable the missing apps again, and if you can't do that, then they aren't compatible.

If we notice that some apps from the backup (made before the update) are missing we ask the user a question if he/she want to restore them manually. So everything works as intended.

Regarding your restore, you need to chown the permissions to www-data.

Hope it helps!

**Comment by enoch85** [comment] 2022-01-31 09:23
We now implemented a fix for this in the update script.

**Closed by enoch85** 2022-01-31 09:23 UTC
Labels: Support

**Comment by jalabaya** [comment] 2022-01-31 09:58
Thank you for the quick reply and action.
