### ISSUE TITLE
passwd: authentication token manipulation error

### ISSUE THREAD

**Issue by De30** [nextcloud/vm#635] opened 2018-08-21 15:29 UTC
Hi, could you help me deal with this error. After trying to install your virtual machine on a new server (Ubuntu 18.04) I can not finish the installation, I get an error message
passwd: authentication token manipulation error
passwd: password unchanged
<img width="795" alt="enter" src="https://user-images.githubusercontent.com/17880554/44411762-44beba00-a535-11e8-9e27-70ef014ce52b.png">

**Comment by enoch85** [comment] 2018-08-21 15:36
Hmm, yeah I saw that yesterday too... Need to figure out what's wrong.

**Comment by enoch85** [comment] 2018-08-21 16:03
### Steps to reproduce

1. Run the startup script
2. Choose to install 
- Fail2ban
- Adminer (but answer no due to HTTP/2)
3. Full Text Search

The this happens:

```
[FULL TEXT SEARCH INSTALLED]
 rm -f /var/scripts/fulltextsearch.sh
+ read -r -u 9 choice
+ rm -f results
+ clear

+ printf '\e[0m\n'

++ cut -d, -f1
++ getent group sudo
++ cut -d: -f4
+ echo 'For better security, change the system user password for [daniel]'
For better security, change the system user password for [daniel]
+ any_key 'Press any key to change password for system user...'
+ local 'PROMPT=Press any key to change password for system user...'
++ printf '\e[0;32mPress any key to change password for system user...\e[0m'
+ read -r -p 'Press any key to change password for system user...' -n1 -s
Press any key to change password for system user.../dev/fd/63: line 687: read: read error: 0: Resource temporarily unavailable
+ echo

+ true
++ getent group sudo
++ cut -d: -f4
++ cut -d, -f1
+ sudo passwd daniel
Enter new UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged
+ true
```

**Comment by enoch85** [comment] 2018-08-21 16:05
@morph027 Seems to have something to do by the `any_key` function... I think. Haven't tested. 

Do you have time to have a quick look?

**Comment by enoch85** [comment] 2018-08-21 16:19
@morph027 No need, think I found the cause. Just committed to master. Will test it soon.

**Comment by enoch85** [comment] 2018-08-21 16:26
@morph027 It complains about line 687 which indeed is the `any_key` function.

**Comment by De30** [comment] 2018-08-21 17:10
yes indeed, if you do not install Full Text Search then everything is fine

**Comment by enoch85** [comment] 2018-08-21 17:16
@Ark74 Hmmm

> yes indeed, if you do not install Full Text Search then everything is fine

Just tested myself to install ALL apps separately, the only time it failed was with Full Text Search. Please help me debug this.

**Comment by Ark74** [comment] 2018-08-21 17:28
The latest version of Full Text Search is having issues (because of the update 0.99) , installing a new instance and updating will fail @daita would know more.

What I can add is that seems the read only rest configuration is not well recognized, special notice on "\Forbidden403Exception" part.

```
Options: []
Memory: 39 MB
┌─ Indexing  ────
│ Provider: Files                Account: User
│ Action: indexChunk
│ Document: 
│ Info: httpd/unix-directory
│ Title: 
│ Content size: 
│ Result: 
└──
┌─ Status ────
│ Progress:      0/2308   done
│ Error:    168/168
│ Exception: Elasticsearch\Common\Exceptions\Forbidden403Exception
│ Message: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
│ 
│ 
│ Index: files:43059
└──
## f:first error ## h/j:prec/next error ## d:delete error ## l:last error
## q:quit ## p:pause
```
Maybe we could open a issue at FTS itself to follow up.

**Comment by enoch85** [comment] 2018-08-21 17:29
Will try not to index and see what happens. I'll be back soon when I've tested.

**Comment by daita** [comment] 2018-08-21 17:31
The only issue I had lately with readonlyrest is : https://forum.readonlyrest.com/t/elasticsearch-6-3-cluster-not-coming-up-after-installing-latest-plugin/645

Could it be related ?

**Comment by daita** [comment] 2018-08-21 17:32
Also @enoch85 & @ark74, which one of you will be at the conf ? :)

**Comment by Ark74** [comment] 2018-08-21 17:32
Here the test,

```
occ fulltextsearch:test
 
.Testing your current setup:  
Creating mocked content provider. ok  
Testing mocked provider: get indexable documents. (2 items) ok  
Loading search platform. (Elasticsearch) ok  
Testing search platform. ok  
Locking process ok  
Removing test. ok  
Pausing 3 seconds 1 2 3 ok  
Initializing index mapping. ok  
Indexing generated documents. fail  
Error detected, unlocking process ok 
                                                                                                                                                                                                          
  [OCA\FullTextSearch\Exceptions\DatabaseException]                                                                                                                                                       
  An exception occurred while executing 'INSERT INTO `oc_fulltextsearch_indexes` (`owner_id`, `provider_id`, `document_id`, `source`, `err`, `message`, `status`, `options`, `indexed`) VALUES(?, ?, ?,   
  ?, ?, ?, ?, ?, ?)' with params ["user1", "test_provider", "license", "", 2, "[{\"message\":\"blocked by: [FORBIDDEN\\\/12\\\/index read-only \\\/ allow delete (api)];\",\"exception\":\"Elasticsearch  
  \\\\Common\\\\Exceptions\\\\Forbidden403Exception\",\"severity\":3},{\"message\":\"blocked by: [FORBIDDEN\\\/12\\\/index read-only \\\/ allow delete (api)];\",\"exception\":\"Elasticsearch\\\\Common  
  \\\\Exceptions\\\\Forbidden403Exception\",\"severity\":3}]", 12, "[]", 1534872680]:                                                                                                                     
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'license' for column 'document_id' at row 1                                                                                     
                                                                                                                                                                                                          

fulltextsearch:test [--output [OUTPUT]] [-j|--json] [-d|--platform_delay PLATFORM_DELAY]
```

**Comment by Ark74** [comment] 2018-08-21 17:33
Conf?

> Also @enoch85 & @Ark74, which one of you will be at the conf ? :)

Where?

**Comment by enoch85** [comment] 2018-08-21 17:34
Yup **confirmed**: When removing the indexing of the files, everything works as expected, so FTS is broken. Will comment out the indexing for now.

@daita Please let me know when this issue is fixed.

**Comment by daita** [comment] 2018-08-21 17:34
Berlin, this week end ? [Nextcloud 2018](https://sched.eventyay.com/NextcloudConference2018/tracks.html)

Also: https://github.com/nextcloud/fulltextsearch/issues/361 (fixed)

**Comment by enoch85** [comment] 2018-08-21 17:36
> Berlin, this week end ? Nextcloud 2018

yes, I'll go on Thursday and be there until Saturday. Will you come?

**Closed** 2018-08-21 17:35 UTC
Labels: bug

**Comment by Ark74** [comment] 2018-08-21 17:39
Ohh, really? already?
Wow time flies, no sorry I wasn't aware, besides I'm really full, have fun!
Maybe 2019

**Comment by enoch85** [comment] 2018-08-21 17:41
@daita Will the cron.php take care of indexing even if it's not done from start? In that case we can skip it as it's prune to error out anyway.

**Comment by daita** [comment] 2018-08-21 17:42
So @enoch85 is the one to talk about the VM ?  
I have a workshop on fulltextsearch saturday afternoon.

no, the cron will only do something after a first index is complete

**Comment by daita** [comment] 2018-08-21 17:42
Hint; if you don't reset the index, the cron will think that an earlier version of FTS already complete the index

**Comment by enoch85** [comment] 2018-08-21 17:45
> So @enoch85 is the one to talk about the VM ?

Yup, I'm scheluded for around 12:00 something something.

> Hint; if you don't reset the index,  

We don't reset any index in the VM scripts, we only do the first index.

**Comment by daita** [comment] 2018-08-21 17:53
The issue with the database is when you do the ./occ full:test  
The issue about readonlyrest/Forbidden, I have no clue about it.
