### ISSUE TITLE
Apache will not restart

### ISSUE THREAD

**Issue by amurdock37** [nextcloud/vm#2295] opened 2022-05-06 16:31 UTC
### Steps To Reproduce

systemctl restart apache2

### Expected Result

To activate the new configuration, you need to run:
  systemctl restart apache2
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed

### Actual Result

To activate the new configuration, you need to run:
  systemctl restart apache2
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed

### Additional Context

apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-05-06 16:34:05 UTC; 22s ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 14258 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
        CPU: 21ms

May 06 16:34:05 localhost systemd[1]: Starting The Apache HTTP Server...
May 06 16:34:05 localhost apachectl[14261]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using ::1. Set the 'ServerName' directive globally to s>
May 06 16:34:05 localhost apachectl[14258]: Action 'start' failed.
May 06 16:34:05 localhost apachectl[14258]: The Apache error log may have more information.
May 06 16:34:05 localhost systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
May 06 16:34:05 localhost systemd[1]: apache2.service: Failed with result 'exit-code'.
May 06 16:34:05 localhost systemd[1]: Failed to start The Apache HTTP Server.
~

### Build Version

24

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 LTS
1 CPU Core 2GB Ram

**Comment by enoch85** [comment] 2022-05-06 18:46
Thanks for posting, can you describe a little more exaclty which steps you took to reproduce this? I can't make it happen, and it works for me on all the installations I did.

Did you for example install any special app, or enabled some kind of config, or TLS?

**Comment by amurdock37** [comment] 2022-05-06 19:11
I believe the mess up point is when the cert bot was trying to cert the desec domain. I would have to go through the script again. To see, but it seems it may have not certified the domain name.

**Comment by amurdock37** [comment] 2022-05-06 19:13
The process' exit code is 'exited' and its exit status is 1.
May 06 16:34:05 localhost systemd[1]: apache2.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit apache2.service has entered the 'failed' state with result 'exit-code'.
May 06 16:34:05 localhost systemd[1]: Failed to start The Apache HTTP Server.
░░ Subject: A start job for unit apache2.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit apache2.service has finished with a failure.
░░
░░ The job identifier is 2357 and the job result is failed.
May 06 17:51:23 localhost systemd[1]: Starting The Apache HTTP Server...
░░ Subject: A start job for unit apache2.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit apache2.service has begun execution.
░░
░░ The job identifier is 3245.
May 06 17:51:23 localhost apachectl[14952]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using ::1. Set the 'ServerName' directive globally to s>
May 06 17:51:23 localhost apachectl[14949]: Action 'start' failed.
May 06 17:51:23 localhost apachectl[14949]: The Apache error log may have more information.
May 06 17:51:23 localhost systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit apache2.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
May 06 17:51:23 localhost systemd[1]: apache2.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit apache2.service has entered the 'failed' state with result 'exit-code'.
May 06 17:51:23 localhost systemd[1]: Failed to start The Apache HTTP Server.
░░ Subject: A start job for unit apache2.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit apache2.service has finished with a failure.
░░
░░ The job identifier is 3245 and the job result is failed.

**Comment by enoch85** [comment] 2022-05-06 19:24
Hmm, so you got this errors after adding deSEC?

**Comment by amurdock37** [comment] 2022-05-06 19:30
Yes, DeSEC installed fine but it seemed a long time for certbot to certify then it would like restart the apache service. The registration of deSEC was successful but I believe the issue lies in certbot certifying or lack there of.

**Comment by enoch85** [comment] 2022-05-06 22:22
Ok then, at least I have a test case.

**Comment by enoch85** [comment] 2022-05-07 08:46
This is now fixed, please try again and report back!

**Closed by enoch85** 2022-05-07 08:46 UTC
Labels: bug

**Comment by amurdock37** [comment] 2022-05-07 16:39
Worked just fine. Thank you.
