### ISSUE TITLE
Activate TLS error: unrecognized arguments: --key-type ecdsa

### ISSUE THREAD

**Issue by MarkWieczorek** [nextcloud/vm#2263] opened 2022-03-23 16:26 UTC
### Steps To Reproduce

I bought a minicomputer from hanssonit.se with nexcloud preinstalled about 6 months ago. When running the initial setup script, I choose to activate TLS using a domain name that I own. Everything worked fine, but since then I bought a new domain name and would like to update the lets encrypt certificates to use this new domain. 

Re-running the `Nextcloud VM - 2022 - Activate TLS` script however, fails with the errors `certbot: error: unrecognized arguments: --key-type ecdsa`. As far as I can tell, there are no problems with port forwarding, or the dns, so I am confused. The GUI interface gives me the following errors:

>It seems like no certs were generated when trying to validate them with the standalone method. We will retry.
>It seems like no certs were generated when trying to validate them with the dns method. We have exhausted all the methods. Please check your DNS and try again.

and here is full output from the terminal:
```
$ sudo bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection...
Downloading the Server Configuration Menu...
Downloading the Let's Encrypt script...

Checking if log10.xyz exists and is reachable...
Doing a DNS lookup for log10.xyz...
Server:		9.9.9.9
Address:	9.9.9.9#53

Non-authoritative answer:
Name:	log10.xyz
Address: 78.201.156.222

DNS seems correct when checking with nslookup!
DNS seems correct when checking with dig!
Testing if network is OK...
Checking connection...
Checking if port 80 is open with https://www.networkappers.com/tools/open-port-checker...
Port 80 is open on 78.201.156.222!
Checking if port 443 is open with https://www.networkappers.com/tools/open-port-checker...
Port 443 is open on 78.201.156.222!
certbot 0.40.0
certbot 0.40.0
Getting current PHP-version...
PHPVER=7.4
/etc/apache2/sites-available/log10.xyz.conf was successfully created.
48690
48692
48693
48694
48695
48696
48697
48698
48699
48700
48701
48702
48703
48704
48705
48706
48707
48708
48709
48710
48711
48712
48713
48714
48715
48716
48717
48718
48719
48720
48721
48722
48723
48724
48725
48726
48727
48728
48729
48730
48731
48732
48733
48734
48735
48736
48737
48738
48739
48740
48741
Site 000-default already disabled
Trying to generate certs and validate them with standalone method.
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --key-type ecdsa
Trying to generate certs and validate them with dns method.
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --key-type ecdsa
snap "certbot" is not installed
```

Any ideas would be much appreciated!

### Expected Result

I expect that re-running activate TLS with a different domain name should work.

### Actual Result

Activate TLS fails, with the error `certbot: error: unrecognized arguments: --key-type ecdsa`

### Additional Context

The only thing that could be different is that the new domain name use DNSSEC (this wasn't the case with the initial domain I used for the initial setup)

### Build Version

22.2.0

### Environment

By downloading the VM

### Environment Details

Ubuntu Linux 20.04.4

**Comment by enoch85** [comment] 2022-03-23 20:37
Thanks! We'll have a look.

**Comment by enoch85** [comment] 2022-03-24 20:48
Please run this:

1. `sudo bash /var/scripts/update.sh`
2. `sudo bash /var/scripts/menu.sh`
3. Choose Server Configuration --> Activate TLS

You're running an old version of Certbot.

**Comment by MarkWieczorek** [comment] 2022-03-24 22:32
Unfortunately, running the "update" script gives me the following message 

```
Nextcloud VM - 2022 - Nextcloud Update Script                                                                                                                                                      
MySQL/MariaDB is not supported in this script anymore. Please contact us to get support for upgrading your server: https://shop.hanssonit.se/product/premium-support-per-30-minutes/
```

I note that this server was bought 6 months ago, so it is hard to imagine that certbot would have changed much since then.

**Comment by enoch85** [comment] 2022-03-26 08:05
It's absolutley possible that it's old. We changed to certbot snap around 6 months ago. Before that we used the deb certbot.

So, please run:

1. `sudo -i`
2. `nextcloud_occ upgrade`
3. `sudo bash /var/scripts/update.sh`

If that doesn't work, please book support [here](https://shop.hanssonit.se/product/premium-support-per-30-minutes/).

**Comment by MarkWieczorek** [comment] 2022-03-26 08:48
Before I do this, could you let me know what "upgrade" actually does? Does this do a minor or major upgrade to nextcloud? And if so, is this the same and running the upgrade options in the script `sudo bash /var/scripts/menu.sh` ?

Perhaps another option would just be to install the newest version of certbot using snap. For some reason the apt version is really old.

**Comment by enoch85** [comment] 2022-03-26 08:53
The commands will hopefully update your Nextcloud so that you can run the other commands I've sent. It will also update your certbot installation: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L357-L373

I'll close this issue since it's not a bug. You're free to book support if you don't manage to fix it on your own.

Thanks!

**Closed by enoch85** 2022-03-26 08:53 UTC
Labels: Support

**Comment by enoch85** [comment] 2022-03-26 23:13
Hey, you can now try again, just added a fix for VMs like yours.

Please report back.

**Comment by MarkWieczorek** [comment] 2022-03-27 08:01
Hi there. I didn't run the `upgrade` script because I am not ready to upgrade nextcloud, and I am not 100% certain what this script does (I can't afford to break anything today...). However, I did uninstall the apt version of certbot and then install the snap version from the command line, exactly as you highlighted in the code above. After re-running the `activate-tls` script from `menu.sh` everything worked fine. I'll try doing a minor upgrade next week, and will get back to you if I encounter any problems.

**Comment by enoch85** [comment] 2022-03-27 08:42
That's exactly what the PR would do for you, automatically.

Anyway, glad you sorted it!
