### ISSUE TITLE
[Suggestion] Replace PostgreSQL command in docs

### ISSUE THREAD

**Issue by KemikalElite** [nextcloud/vm#2452] opened 2023-03-12 20:59 UTC
The PostgreSQL command in the documentation:
```$ sudo -u postgresql psql [database name]```
should be replaced with:
```$ psql -h localhost -U nextcloud_db_user -d nextcloud_db```

The current command does not work out of the box as it should by default.

It's not actually needed to run psql as the postgres user to access the nextcloud database.

When I use the current command in the docs it prompts me for a password for the postgres user and from searching I've learned that the postgres user in postgresql on ubuntu does not have a password set by default.

Rather than editing pg_hba.conf to allow access to the postgres user to set that password it is simpler to just login to the database as the nextcloud database user which does have a password set in config.php

As someone with no prior understanding of how the psql command works, i suggest replacing the command in the docs as it allows the user to access the nextcloud database from the shell with a single command [without needing to change the postgres user password](https://stackoverflow.com/a/10846346).

**Comment by enoch85** [comment] 2023-03-27 16:52
@KemikalElite Thanks, updated the docs to the correct command (it was the wrong user before):
https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=W6ypBePiqQz3_Mp0

**Comment by enoch85** [comment] 2023-03-27 16:53
@HakanP It works here, can't reproduce that one. :/

**Comment by KemikalElite** [comment] 2023-03-27 17:53
> This also seems to be a problem when upgrading. On a newly deployed VM, I get asked for the user postgres password. Both when I try to do a Minor and a Major upgrade. (It's version 25.0.2 in the VM at the moment) `Checking for new Nextcloud version... Latest release is: 26.0.0. Current version is: 25.0.2. New version available, upgrade continues! Checking connection... Backing up files and upgrading to Nextcloud 26.0.0 in 10 seconds... Press CTRL+C to abort. Password for user postgres: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: password authentication failed for user "postgres" Doing pgdump of all databases... Password: pg_dumpall: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: password authentication failed for user "postgres" root@nextcloud:/home/ncadmin# `

I've experienced this. Prior to updating nextcloud the system will do a database backup and it prompted me to manually type the postgres user password. I have VM snapshots so I'll see if I can rollback to repeat the update and get a screenshot or video of it prompting for the password.

I've noticed that the scripts automatically set a random postgres user password during setup and it does show the password very quickly, but if I'm not watching for it it's easy to miss.

**Comment by enoch85** [comment] 2023-03-27 21:13
Which version are you running of the VM, how long since you downloaded the original OVA?

Is it the same thing if you run with the scripts directly?

**Comment by HakanP** [comment] 2023-03-28 05:44
In my case, this is a newly downloaded and installed VM. Had to "restart" since I got problems with PHP-upgrade on my old.
No automatic updates. Same thing both with the update.sh and the nextcloud_update command.

**Comment by enoch85** [comment] 2023-03-28 09:05
> newly downloaded and installed VM

Which version was the VM when you downloaded it the first time?

**Comment by HakanP** [comment] 2023-03-28 09:25
The old one was a couple of years old with Ubuntu 20.04. But there I never had the problem. This is on the latest. But have done two test-installations now with some different choices in the setup, and didn't get the same error. This was in VMware Workstation though, normally I run it in the Virtualization Station on a Qnap. Will do a reinstall and see (even if I already have set a password for the postgres user and have upgraded Nextcloud now, but seems other things also missing like paths to commandos)

**Comment by enoch85** [comment] 2023-04-02 21:08
I have made around 10 upgrades this weekend on various servers, and none if them behaved as explained.

Please download the latest VM and use something else than Virtalbox.

Closing.

**Comment by enoch85** [comment] 2023-04-07 15:14
Fix is now merged, please test.

Closing this issue again.

**Closed** 2023-04-07 15:14 UTC
Labels: bug
