### ISSUE TITLE
[Exception] ONLYOFFICE  cannot be installed 

### ISSUE THREAD

**Issue by Toddehawk** [nextcloud/vm#647] opened 2018-08-31 18:08 UTC
Hi,

When I start the onlyoffice.sh script everything is good untill 
sudo -u www-data php /var/www/nextcloud/occ app:enable onlyoffice

I get this error:
 [Exception]
  App "ONLYOFFICE" cannot be installed because it is not compatible with this version of the server.

Should I have to wait for a new onlyoffice Version?

Thanks!

BR
Thorsten

**Comment by nextcloudvmtester** [comment] 2018-09-03 05:02
Also getting this issue. In my case, I had previously installed Collabora, perhaps that may have caused it?

Additional info: 
Nextcloud 13, installed using VM
Ubuntu 18.04

Running the script originally produced errors that "Cannot be installed at the same time as Collabora", but I uninstalled the app using the web UI and also removed from docker using docker rm -f, after which the onlyoffice.sh script did not complain about Collabora any more.

I also opened an issue on the OnlyOffice Github, see https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/9 .

Any advice welcome, and please feel free to ask for more info if required.

Thanks for your time and help!

**Comment by nextcloudvmtester** [comment] 2018-09-03 05:13
Additionally, after repeating the above steps trying to remove OnlyOffice, I can no longer install Collabora. (It seems like OnlyOffice is installed already. ...)

On this note, what is the recommended method for uninstalling apps that were installed with the above scripts?

**Comment by enoch85** [comment] 2018-09-03 06:06
Duplicate of https://github.com/nextcloud/vm/issues/641

@nextcloudvmtester 

You need to uninstall the app and also remove the docker to be able to install as you can't run Collabora and Onlyoffice next to each other.

**Comment by nextcloudvmtester** [comment] 2018-09-03 14:18
@enoch85 Thanks for the reply.

I'm not too familiar with Nextcloud; could you please give a more detailed list of instructions on how to properly uninstall an app?

I've removed it from using the web GUI (disable and then remove), then removed the docker (docker rm -f <name>), and also erased the folder that the setup scripts look for (richdocuments or onlyoffice, ie. rm -rf /var/www/nextcloud/onlyoffice). Despite that, my Nextcloud instance is currently in a state where I cannot install either package. 

I would appreciate a more detailed list of what to look for, or commands to run. 

Thanks for your help!

**Comment by enoch85** [comment] 2018-09-03 16:28
@nextcloudvmtester [This](https://github.com/nextcloud/vm/blob/master/apps/collabora.sh#L30-L36) is the check that checks if OnlyOffice is installed

So basically:
1. Stop and remove the Docker with `docker stop [image]` and `docker rm -f [image]`
2. Disable and delete everything else related to the app. So disable then delete with `rm -r /var/www/nextcloud/apps/[app]`

Hope it helps!

**Comment by nextcloudvmtester** [comment] 2018-09-04 01:03
@enoch85 Thanks for the more detailed reply. I did all of the above, but the problem still persists. 

I believe the problem is in one of these lines though: https://github.com/nextcloud/vm/blob/19bb705c97cd84161ee1b547f63b7a2fea69f473/apps/onlyoffice.sh#L196-L199

The folder `/var/www/nextcloud/apps/onlyoffice` exists, but I cannot enable the app. The script fails with the error above, and the web GUI shows ONLYOFFICE under Disabled Apps, and the enable button is greyed out. If I find the app in the store, I can press the "Enable" button there, but I get an immediate red box under the enable button with the text `App "ONLYOFFICE" cannot be installed because it is not compatible with this version of the server.`

Fortunately, since I am still setting up the server I can afford to wipe everything and reinstall from scratch, so I'm going to do that next. 

If possible, it would be great if these mutually exclusive scripts could at least warn users (ex. quick text box saying that it is incompatible with the following modules) before installing. An uninstall script for apps in the VM would also be lovely (or tell users to only add/remove apps with the web GUI). Despite this hiccup, Nextcloud has been great, so thanks for your hard work developing it!

**Comment by nextcloudvmtester** [comment] 2018-09-04 05:56
It took a few hours, and several attempts, but I was finally able to install ONLYOFFICE using a fresh install (OS and everything). 

It was hard to tell since the screen only flashed for an instant, but I think the script always reports a failure, even if it is successfully installed. I found that just using the Nextcloud App store was a sufficient way to get it installed eventually.

**Comment by enoch85** [comment] 2018-09-04 06:51
@nextcloudvmtester 

> If possible, it would be great if these mutually exclusive scripts could at least warn users (ex. quick text box saying that it is incompatible with the following modules

Not possible as the app has to be installed to get that error.

> An uninstall script for apps in the VM would also be lovely

PRs are welcome! :)

> It took a few hours, and several attempts, but I was finally able to install ONLYOFFICE using a fresh install (OS and everything).

Great! Then maybe OnlyOffice fixed the issue meanwhile. As I stated earlier this was just temporary as the apps has to be maintained to work. The VM will install them, but we can't control every hour if they work or not. The released versions always work as we test everything before release.

>  I think the script always reports a failure, 

Nope, that's not the logic. It reports an error if it's an error. And the error you saw was due to the app not being compatible at the moment.

Thank you for testing and confirming that everything worked on a fresh install! <3

**Comment by nextcloudvmtester** [comment] 2018-09-04 20:16
Sorry, to clarify, even on the fresh install, the script displayed the same error. I had to use the web GUI to disable, remove, and then reinstall the app. Once installed through the web GUI app store, the installation succeeded.

Glad I could be of some help!

**Comment by enoch85** [comment] 2018-09-04 20:40
Hmm, that's strange. The `occ_command` downloads the app from the app store, so enabling it there should do the same as in the scripts. 

I will install a new server soon, and will test then.

**Comment by alexdaums** [comment] 2018-09-05 09:51
Hello,

I have the same error on a fresh install.

**Comment by enoch85** [comment] 2018-09-05 11:29
@nextcloudvmtester @alexdaums Could you guys please redo the installation, but this time don't install OnlyOffice, and download the script manually after a successful install of the VM, just to see if it's due to running in the setup script?

Thanks!

**Comment by alexdaums** [comment] 2018-09-05 13:29
@enoch85 
I just tested your idea.
And still the same error.

Thank you.

**Comment by enoch85** [comment] 2018-09-05 13:38
> I think ONLYOFFICE updated the image document server and not its application for Nextcloud...

That's exactly my thought as well.

**Closed** 2018-09-05 20:06 UTC
