### ISSUE TITLE
Unable to install TURN server from menu.sh

### ISSUE THREAD

**Issue by ozinfotech** [nextcloud/vm#1389] opened 2020-08-26 17:07 UTC
## Steps to reproduce
1. Run sudo bash /var/scripts/menu.sh
2. Go through the steps up to installing a TURN server

## Expected behaviour
I expected the TURN server to finalize installation.

## Actual behaviour
Receive an error message:
<code>curl: (28) Failed to connect to talk.domain[.org] port 443: Connection timed out</code>

## Server configuration

**Nextcloud server version:** 19.01

**Server OS** (Ubuntu server is default) Ubuntu

**How did you install the VM?** (Scripted install from master **OR** Released version) Hyper-V VM purchased from Hansson IT

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** Yes

## Logs / Screenshots
```
-- Logs begin at Thu 2020-07-16 16:08:59 CDT. --
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.737533 mcu_janus.go:315: Created Janus session 8543873793443358
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738417 mcu_janus.go:322: Created Janus handle 884320408026736
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738462 main.go:199: Using MCU janus at ws://127.0.0.1:8188
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738733 hub.go:283: Using a timeout of 10s for MCU requests
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738789 backend_server.go:94: Using configured TURN API key
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738805 backend_server.go:95: Using configured shared TURN secret
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738818 backend_server.go:97: Adding "turn:cloud.domain[.]org:3478?transport=tcp" as TURN server
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738829 backend_server.go:97: Adding "turn:cloud.domain[.]org:3478?transport=udp" as TURN server
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.738842 backend_server.go:104: No IPs configured for the stats endpoint, only allowing access from 127.0.0.1
Aug 26 11:09:47 cloud.domain[.]org signaling[132346]: 2020/08/26 11:09:47.740218 main.go:274: Listening on 127.0.0.1:8081
```

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Error | user_ldap | Attempt for Paging? 1 |   | 2020-08-26T12:00:05-0500
-- | -- | -- | -- | --
Error | PHP | ldap_search(): Search: Critical extension is unavailable at /var/www/nextcloud/apps/user_ldap/lib/LDAP.php#341 |   | 2020-08-26T12:00:05-0500
Error | user_ldap | Attempt for Paging? 1 |   | 2020-08-26T12:00:04-0500
Error | PHP | ldap_search(): Search: Critical extension is unavailable at /var/www/nextcloud/apps/user_ldap/lib/LDAP.php#341 |   | 2020-08-26T12:00:04-0500
Error | user_ldap | Attempt for Paging? 1 |   | 2020-08-26T12:00:04-0500
Error | PHP | ldap_search(): Search: Critical extension is unavailable at /var/www/nextcloud/apps/user_ldap/lib/LDAP.php#341 |   | 2020-08-26T12:00:04-0500
```

**Comment by enoch85** [comment] 2020-08-27 01:11
@szaimen @morph027 I belive this is end-user related and not a bug per say, what do you think?

@ozinfotech Have you tested the scripts on a totally open network VPS? 

Maybe have a look at your firewall, DNS, or similar to pin down the real issue here.

Thanks!

**Comment by enoch85** [comment] 2020-08-27 01:14
@ozinfotech Is this a local domain only available on LAN.

I mean if curl times out then it's probably not reachable from within the VM due to network restrictions on your end. I might be wronf though.

**Comment by enoch85** [comment] 2020-08-27 12:01
@ozinfotech  I just tested again, and I can't reproduce it.

Can you please provide more details regarding your setup?

**Comment by ozinfotech** [comment] 2020-08-27 12:52
@enoch85 The site is available on the open Internet. I have it behind a IIS reverse proxy, however, and that sounds like it will be the cause. I have the same settings on the proxy for the **talk** domain as the **cloud** domain. There must be something going on with that port.

On the LAN, I can see the following message: Hi there! :) If you see this page, the Apache2 proxy for Talk Signaling Server is up and running.

On the WAN, or from a home computer, it just redirects to the **cloud** login, but still using the **talk** domain.

Any suggestions I can try on the proxy?

**Comment by ozinfotech** [comment] 2020-08-27 14:11
I wondered if it had anything to do with the port, but the port seems to work just fine. It is the signaling server that seems to hang up and I'm not sure what or how it is attempting to connect since the port doesn't show up on it like it does the STUN and TURN servers.

**Comment by enoch85** [comment] 2020-08-27 15:44
> I have it behind a IIS reverse proxy,

>  There must be something going on with it.

I'm 99.9% sure that's the cause.

The traffic is already proxied inside the VM, so if you want a frontend proxy you need to proxy it to Bitwarden directly.

Closing as a support ticket.

**Closed** 2020-08-27 15:44 UTC
Labels: Support

**Comment by enoch85** [comment] 2020-08-27 15:46
@ozinfotech Sorry, can't help you with IIS.

**Comment by ozinfotech** [comment] 2020-08-27 16:18
Not a problem. I appreciate the thoughts up front. I didn't even consider IIS being the issue.

**Comment by enoch85** [comment] 2020-08-27 19:29
@ozinfotech  Would be interesting though to know the outcome. :)
