### ISSUE TITLE
Problem with creating LE-SSL Cert

### ISSUE THREAD

**Issue by bobdig** [nextcloud/vm#859] opened 2019-07-03 11:01 UTC
## Steps to reproduce
1.Installed  new ncvm today after fresh dl today
2.run it

## Expected behaviour
It should create LE-SSL Cert

## Actual behaviour
it is not doing it. Not in the initial setup process and not after manual start afterwards. 
> Is this correct?XXX ([y]es or [N]o): y
> Checking if XXX exists and is reachable...
> Doing a DNS lookup for XXX...
> DNS seems correct when checking with nslookup!
> DNS lookup failed with dig. The external IP (XXX) address of this serve                       r is not the same as the A-record.
> Please check your DNS settings! Maybe the domain isn't propagated?
> Please check https://www.whatsmydns.net/#A/XXX if the IP seems cor                       rect.
> ncadmin@nextcloud:~$ Nope, it's not there. You have to create XXX                        and point 

I use a subdomain (xxx.dyndns.org). 
 https://www.whatsmydns.net showed no problems. 
Worked before. So there is something not ok.

**Comment by bobdig** [comment] 2019-07-03 11:06
I was just curious, wanted to find out if the included setup for LE would allow for an wildcard cert, but it wont even do the setup, so I couldn't check it out. Would like to have such an option if possible, because I got my first own domain. ;)

**Comment by enoch85** [comment] 2019-07-03 12:32
The script does checks to check if everything is prepared for the script to succeed. If things aren't setup correctly it will stop executing, by design.

That is so that you don't install any unnecessary packages, and is left with a failing setup. If the checks pass, it's almost guaranteed that it will work. 

You could hash them out in the code just for testing though.

Wilcards should be supported with the DNS option which is implemented in the scripts as well.

**Comment by enoch85** [comment] 2019-07-03 12:33
I can also add that I've made the checks stricter now than before, hence it might not proceed in some edge cases anymore.

**Comment by bobdig** [comment] 2019-07-03 12:38
But I have no edge case, just a subdomain with dyndns. Tested it three times. Why you closed it?

**Comment by enoch85** [comment] 2019-07-03 12:53
I was closing since the error says:

> DNS lookup failed with X The external IP (XXX) address of this serve r is not the same as the A-record.

So in my world that means that the DNS isn't propagated yet.

The thing is also that I helped a customer yesterday with setting up SSL and it worked out of the box, and since nothing changed that tells me that it's a configuration issue on the end-users end.

I will run some tests and leave this open until I've confirmed it's working or not. Sorry for being so quick on the close button, I get theese types of reports from time to time, and in 99% of the cases, it's either:
1. Propagation not done yet
2. Some other error caused by the end-user.

**Comment by enoch85** [comment] 2019-07-03 12:54
[This](https://github.com/nextcloud/vm/blob/master/lib.sh#L213-L240) is the logic if you want to test for yourself. Thanks. :)

**Comment by bobdig** [comment] 2019-07-03 13:05
I am no programmer at all just a novice user, but interestingly my subdomain includes the word "dig" which I also find in your code, so maybe there is the problem?

**Comment by enoch85** [comment] 2019-07-03 13:22
OK, so can you post the result of: http://mittip.se?

**Comment by enoch85** [comment] 2019-07-03 13:22
For reference: bobdig.dyndns.org = 5.28.113.194

**Comment by bobdig** [comment] 2019-07-03 13:24
It is the same

**Comment by bobdig** [comment] 2019-07-03 13:37
I also made a port test right after the failing of the LE-Script and it says that the ports are "closed". I don't know if this is the correct behavior. They are open in the router, all other ports are "stealth".

**Comment by bobdig** [comment] 2019-07-03 14:06
PS C:\Windows\system32> nslookup bobdig.dyndns.org resolver1.opendns.com
Server:  resolver1.opendns.com
Address:  208.67.222.222

I think the opendns resolver is just trash.

**Comment by enoch85** [comment] 2019-07-03 14:13
What happens if you comment out (put a # in front of the test) and run the script?

You can check open ports here: https://www.yougetsignal.com/tools/open-ports/, it seems like they are open and the script should recognize that in the second test.

**Comment by enoch85** [comment] 2019-07-03 14:22
Also, since the IP now seems to be propagated, could you please test the original script "as is" just to check if the original issue was a propagation issue?

Thanks.

**Comment by bobdig** [comment] 2019-07-03 14:36
> What happens if you comment out (put a # in front) the test and run the script?
hard for me to do, to be honest. It also looks different then the link you gave before.

>Also, since the IP now seems to be propagated, could you please test the original script "as is" just to >check if the original issue was a propagation issue?
Doesn't do it. But there is one more thing I forgot to mention. Many Cable-ISP do, and so does mine, some sort of NAT, so that the Router can not see the external WAN-IP, but a [100.6something IP](https://db-ip.com/100.65.0.1). So if your script also checks this, it will fail. But I as a user can open Ports with no problem...

**Comment by enoch85** [comment] 2019-07-03 14:56
It would be (is) hard to programmatically ensure that every single router on the planet works with the scripts with no user interference. Sure, maybe program a DynDNS service would work - but my time is limited. I don't even know if there are any DynDNS with an API that supports account registratation with some bash scripts, would have to investigate that.

As it is now it works with the most setups, I just tested on DigitalOcean (which I use as a reference) and it setup without any issues at all. So in my world there are no script error per say, more like a limitation on the end-users side, or that something is wrong in the end-users setup. IN your case it seems to be a limitation.

That said, if your ISP is blocking you in some way, I'm sorry. Change ISP ;). Jokes aside, the script isn't designed to handle edge cases like yours. I think it would be possible to solve, but that would require some support.

**Comment by bobdig** [comment] 2019-07-03 14:56
> 
> 
> What happens if you comment out (put a # in front) the test and run the script?
> 
> You can check open ports here: https://www.yougetsignal.com/tools/open-ports/, it seems like they are open and the script should recognize that in the second test.

I think I made it, now the script is running.

**Comment by bobdig** [comment] 2019-07-03 14:58
> 
> 
> It would be (is) hard to programmatically ensure that every single router on the planet works with the scripts with no user interference. Sure, maybe program a DynDNS service would work - but my time is limited. I don't even know if there are any DynDNS with an API that supports account registratation with some bash scripts, would have to investigate that.
> 
> As it is now it works with the most setups, I just tested on DigitalOcean (which I use as a reference) and it setup without any issues at all. So in my world there are no script error per say, more like a limitation on the end-users side, or that something is wrong in the end-users setup. IN your case it seems to be a limitation.
> 
> That said, if your ISP is blocking you in some way, I'm sorry. Change ISP ;). Jokes aside, the script isn't designed to handle edge cases like yours. I think it would be possible to solve, but that would require some support.

The only problem is that your script is checking against the router I think. Didn't do it before. So I thin it would be easily fixable.

**Comment by enoch85** [comment] 2019-07-03 14:59
> I think I made it

Great! :+1: 

It would be interesting to see the actual output of the `domain_check` looks like.

> The only problem is that your script is checking against the router I think. It didn't do it before. So I think it would be easily fixable.

Yeah, the check is more strict now.

**Comment by bobdig** [comment] 2019-07-03 15:01
> It would be interesting to see the actual output of the `domain_check` looks like.
I don'T know what you mean by that. I commented out the right thing it seems.

**Comment by enoch85** [comment] 2019-07-03 15:02
You don't have a valid SSL cert yet. Just checked.

**Comment by enoch85** [comment] 2019-07-03 15:02
Email me your Teamviewer details and I'll have a quick look. 

github at hanssonit dot se

**Comment by bobdig** [comment] 2019-07-03 15:06
Did it.

**Comment by enoch85** [comment] 2019-07-03 15:29
The `dig` test failed since it resolves the actuial IP of the host it fails when using DynDNS. 

So the script does what it's intended to do. 

Will add some info about when using DynDNS.

**Closed by enoch85** 2019-07-03 15:29 UTC
Labels: Support, User configuration

**Comment by bobdig** [comment] 2019-07-03 15:32
@enoch85 I don't think so, the problem is not the use of dyndns but that my ISP is doing that kind of NAT with the 100. IP. But thanks for looking into it.

**Comment by bobdig** [comment] 2019-07-03 15:39
And please delete [this](https://github.com/nextcloud/vm/issues/859#issuecomment-508090695), thanks again.

**Comment by enoch85** [comment] 2019-07-03 16:36
Yes, the issue is DynDNS. Check your DNS IP now, it's different. :)

The script checks if the WAN IP (your external IP in your router) is the same as the DNS A record, if not, then it "fails".

I'm looking into now if this can be improved.

**Comment by bobdig** [comment] 2019-07-03 16:51
And again, no. I deliberately changed my WAN-IP but what my router is seeing is not my WAN-IP, it is an CGN-IP from my ISP, which is again, not my WAN-IP. So it differs and that is the problem or to be more precise, that the new script is checking and that that CGN-IP is reported. But that has nothing to do with DDNS in general.

**Comment by enoch85** [comment] 2019-07-03 18:35
The current solution is to hash out the check if you are running DDNS, but I will make it optional if it fails instead. Working on it right now.

Had another support session recently with the same error.

**Comment by bobdig** [comment] 2019-07-03 18:42
Anyhow, if it will work, perfect. 🥇
