### ISSUE TITLE
Problem while installing Python packages / renewing LE cert

### ISSUE THREAD

**Issue by anubis-genix** [nextcloud/vm#775] opened 2019-01-23 10:15 UTC
Python package installation broke something while I tried to renew my letsencrypt certificate.

## Steps to reproduce
1. ./letsencrypt-auto renew on 15.0.0

## Expected behaviour
Certbot renewing LE certificate

## Actual behaviour
Certbot has problems setting up the virtual environment after 'updating' Python packages

## Server configuration

**Nextcloud server version:** (see your admin page)
15.0.0 before the Python error. Updated to 15.0.2 afterwards (still not working).

**Server OS** (Ubuntu server is default)
Ubuntu 16.04.5 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version

## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes

#### Log file (/mnt/ncdata/nextcloud.log)
no noticable entries prior to the update process from 15.0.0 to 15.0.2

#### Installation log (command output)
https://0bin.net/paste/wwGipb5h6xU-OSRc#DlDV-aIRieWLeT7ZehJV4x1fbpaPlVHj+6/E7R+bqCY

**Comment by enoch85** [comment] 2019-01-23 11:30
Thanks for your report.

When did you install the VM for the first time?

**Comment by enoch85** [comment] 2019-01-23 11:36
Aah this is 16.04. It's not maintained anymore so there is no way for me to fix this in the code. 

This is more of a support question and not a bug with the scripts as the issue you are referring to is already fixed in master. We don't even use the git version of Lets Encrypt anymore.

You have two options:
1. Ask in the [forum](https://help.nextcloud.com)
2. Buy [premium support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) and get it done while you sit back and relax.

**Closed by enoch85** 2019-01-23 11:36 UTC
