### ISSUE TITLE
Minor upgrade from 22.2.7 to 22.2.8 deletes allmost all apps

### ISSUE THREAD

**Issue by MarkWieczorek** [nextcloud/vm#2335] opened 2022-05-21 08:21 UTC
### Steps To Reproduce

I am using the nextcloud VM as shipped preinstalled by hanssonit on a nextcloud homeserver. Previously, I have performed minor updates with no major problems. However, with the minor upgrade from 22.2.7 to 22.2.8, almost all apps were deleted and can not be reinstalled from the ncwebadmin account. In particular, this includes calander, music, gpoddersync, news, tasks, notes, and 2FA. The only apps that are installed and working are photos and files.

While upgrading from the terminal, I was presented with some warning/error with these apps, asking if I would like to install them from a backup even though it may not be able to verify the integrity (or something like that). The default answer was NO, so I clicked on the default that thinking that I would be able to reinstall them later. Unfortunately, when you open the ncwebadmin account and search in the apps, these apps are nowhere to be found. I have no idea how to re-install them, nor if the data associated with these apps was deleted.

### Expected Result

I expect that a minor update should work with no problems, and that all compatible apps should be left untouched.

### Actual Result

Allmost all apps are removed, and there is no way to reinstall them (and who knows about the data....)

### Build Version

22.2.8

### Environment

By downloading the VM

### Environment Details

Nextcloud Home Server sold by Hansonit.

**Comment by MarkWieczorek** [comment] 2022-05-21 08:36
Further info:
In the upgrade log it first notes
```
Trying to automatically update all Nextcloud apps...
Your apps are already up to date!
```
Then later
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode already disabled
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: contacts
Disabled incompatible app: extract
Disabled incompatible app: files_markdown
Disabled incompatible app: gpoddersync
Disabled incompatible app: music
Disabled incompatible app: news
Disabled incompatible app: notes
Disabled incompatible app: tasks
Disabled incompatible app: twofactor_totp
Starting code integrity check...
Finished code integrity check
Update successful
```

**Comment by enoch85** [comment] 2022-05-21 08:57
We use the regular `occ upgrade` command when upgrading Nextcloud. Actually, all the functions we use are built into Nextcloud and does not differ from the default way if doing things. 

In other words, if your apps are disabled it'sdue to that they probably not are compatiblez or that something is wrong with Nextclouds updater.

To reinstall them, please copy them over to the apps folder in Nextcloud from the folder in /mnt/NCBACKUP/apps.

After that you have to re-enable them in the GUI. Warnings might occur, and it might not. 

Either way, using the scripts are a good way of keeping your data safe.

FYI @szaimen, don't know if we can improve this further to take NC "bugs" into account?

**Comment by szaimen** [comment] 2022-05-21 09:05
This is not a bug. It is exptected that non-default apps get disabled during the upgrade procedure but they are also automatically enabled again after the upgrade.

**Comment by szaimen** [comment] 2022-05-21 09:08
> FYI @szaimen, don't know if we can improve this further to take NC "bugs" into account?

We may change the default for the question if you want to restore from backup to yes?

**Comment by szaimen** [comment] 2022-05-21 09:13
But honestly this should probably be reported to the server repo as apps should obviously get automatically reenabled again after running `occ upgrade`. @MarkWieczorek can you please open a new issue here https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+ and fill out all requested data? Thank you! :)

**Comment by MarkWieczorek** [comment] 2022-05-21 09:16
> In other words, if your apps are disabled it's due to that they probably not are compatible or that something is wrong with Nextclouds updater.

All the apps that were disabled/deleted are compatible with 22.2.8, so the problem is with the `/var/scripts/update.sh minor` script.

**Comment by MarkWieczorek** [comment] 2022-05-21 10:00
For those in the same situation, here are the steps to follow to fix this problem

```
sudo cp -R /mnt/NCBACKUP/apps/twofactor_totp /var/www/nextcloud/apps
sudo chown -R www-data:www-data twofactor_totp/
```
Then in the ncwebadmin account, go to apps, your apps, and then enable the app. I didn't encounter any errors, and no data was lost!

**Comment by enoch85** [comment] 2022-05-21 10:19
Thanks for reporting @MarkWieczorek!

We'll close this since the issue lays elsewhere.

**Closed by enoch85** 2022-05-21 10:19 UTC
Labels: Support
