### ISSUE TITLE
Latest Update broke docker

### ISSUE THREAD

**Issue by tiagoefreitas** [nextcloud/vm#713] opened 2018-11-18 20:01 UTC
With latest update I got this error:
Failed to start docker.service: Unit docker.socket not found

Trying to fix it, copied /lib/systemd/system/docker.service to /etc/systemd/system/ again, and added  "--storage-driver=devicemapper" to ExecStart but it fails:

INFO[2018-11-18T20:59:44.991739905+01:00] parsed scheme: "unix"                         module=grpc
INFO[2018-11-18T20:59:44.991767056+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2018-11-18T20:59:44.991828102+01:00] parsed scheme: "unix"                         module=grpc
INFO[2018-11-18T20:59:44.991849189+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
ERRO[2018-11-18T20:59:44.992001497+01:00] Failed to GetDriver graph                     driver=devicemapper error="graphdriver plugins are only supported with experimental mode" home-dir=/var/lib/docker

May want to fix onlyoffice.sh

**Comment by tiagoefreitas** [comment] 2018-11-18 20:09
Problem was ubuntu docker update missing devicemapper plugin, see here:

https://github.com/docker/for-linux/issues/452

**Comment by enoch85** [comment] 2018-11-18 20:16
Let's wait and see if it will remain or if we (OnlyOffice, Collabora and everyone else using devicemapper) have to change to something else

**Comment by enoch85** [comment] 2018-11-18 20:20
Could you please try a fresh install and see if it works with `overlay2` instead here: https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh#L83-L87?

Thanks!

**Comment by tiagoefreitas** [comment] 2018-11-18 20:34
Is devicemapper required?
I can't do a fresh install but I can try to change it and test.

**Comment by tiagoefreitas** [comment] 2018-11-18 20:35
Doesn't work for  me, but my system is modified I'm running zfs on root filesystem with luks.

'overlay2' is not supported over zfs          storage-driver=overlay2

**Comment by enoch85** [comment] 2018-11-19 12:05
@tiagoefreitas Ah ok I see. It would be very helpful if you could put up a test system / VM just to test if it works with `overlay2`. In that case we'll change.

IIRC it didn't work with `overlay2` and that's why we went with `devicemapper`.

**Comment by enoch85** [comment] 2018-11-19 18:23
I just updated my server to the latest version (Ubuntu packages including Docker) and the Collabora docker image, everything is working even after a reboot. Hmm...

**Comment by enoch85** [comment] 2018-11-19 18:40
OK, I just confirmed, it broke on my other server when changing to overlay2.

So I will hold the docker update for now.

**Comment by enoch85** [comment] 2018-11-19 18:59
For referance: https://github.com/nextcloud/vm/pull/546

**Comment by enoch85** [comment] 2018-11-19 19:08
Posted bug report with Collabora: https://github.com/nextcloud/richdocuments/issues/313

**Comment by enoch85** [comment] 2018-11-19 19:10
And with Onlyoffice: https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/issues/3

**Comment by enoch85** [comment] 2018-11-19 19:11
This is quite interesting though.... 

https://fribeiro.org/tech/2018/02/13/collabora-docker-nextcloud/

**Comment by tiagoefreitas** [comment] 2018-11-19 19:34
Wont work for me anyway since it doesn’t support zfs...

**Comment by enoch85** [comment] 2018-11-19 20:01
> doesn’t support zfs...

You win some, you loose some. :)

**Comment by tiagoefreitas** [comment] 2018-11-20 21:15
Found this in docker info:
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support

It means performance can be improved?

I found when changing storage drivers, this needs to be done, will test better:
https://meta.discourse.org/t/how-to-change-storage-backend-in-docker/75352

**Comment by enoch85** [comment] 2018-11-26 18:03
@tiagoefreitas Do you think you could prepare a PR for storing it in ZFS? Would be great to have a future proof way of doing it since devicemapper isn't optimal.

**Comment by enoch85** [comment] 2018-11-26 18:32
Or I maybe solved it with overlay2 instead. Let's see if collabora works as well... Onlyoffice is fixed anyway.

**Comment by enoch85** [comment] 2018-11-26 19:14
It works with Collabora as well. This issue is now fixed.

**Closed by enoch85** 2018-11-26 19:14 UTC
Labels: bug
