### ISSUE TITLE
Internal Server Error after upgrade to Nextcloud 15.0.2

### ISSUE THREAD

**Issue by Shoghi74** [nextcloud/vm#777] opened 2019-01-25 11:56 UTC
Hi,

We ran the script to upgrade our Nexcloud VM. The script does not report error during the upgrade.
After the upgrade, when launching the web interface, we had the following error:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

-->
## Steps to reproduce
1. Just upgrade via sudo bash /var/scripts/update.sh
2.
3.

## Expected behaviour
New version working

## Actual behaviour
Internel error

## Server configuration

**Nextcloud server version: 15.0.2

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
fixe ip address.

**Is port 80 and/or 443 open? yes

#### Log file (/mnt/ncdata/nextcloud.log)
Last logs:
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:36+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:47+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:47+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Clear every generated avatar on major updates","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:58+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Avatar cache cleared","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:59+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add preview background cleanup job","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:19:59+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:00+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair pending cron jobs","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:00+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No need to repair pending cron jobs.","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:01+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Extract the vcard uid and store it in the db","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:01+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Fixed 5 vcards","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:02+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:25+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"14.0.4.2"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:25+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"15.0.2.0"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:25+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"15.0.2.0"}
{"reqId":"zqGxGmvhcpdCLjmb5zmz","level":1,"time":"2019-01-14T22:20:26+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"15.0.2.0"}

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment] 2019-01-25 14:55
When was the first time you installed and downloaded the VM, which version?

Can you show me the logs for:
- Apache2
- PHP-FPM

Thanks!

**Comment by Shoghi74** [comment] 2019-01-25 15:04
Hi,

The initial version was 13 (I think), it was one of your appliance with 50 Gb.

The Apache error : 

[Fri Jan 25 06:25:30.434005 2019] [mpm_prefork:notice] [pid 1647] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Fri Jan 25 06:25:30.434028 2019] [core:notice] [pid 1647] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 25 12:05:38.246594 2019] [mpm_prefork:notice] [pid 1647] AH00169: caught SIGTERM, shutting down
[Fri Jan 25 12:07:19.289006 2019] [mpm_prefork:notice] [pid 2965] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Fri Jan 25 12:07:19.346440 2019] [core:notice] [pid 2965] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 25 12:27:13.894835 2019] [mpm_prefork:notice] [pid 2965] AH00169: caught SIGTERM, shutting down
[Fri Jan 25 12:29:21.634909 2019] [mpm_prefork:notice] [pid 2636] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Fri Jan 25 12:29:21.802430 2019] [core:notice] [pid 2636] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 25 12:42:20.881789 2019] [mpm_prefork:notice] [pid 2636] AH00169: caught SIGTERM, shutting down
[Fri Jan 25 12:42:21.024088 2019] [mpm_prefork:notice] [pid 31030] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Fri Jan 25 12:42:21.024145 2019] [core:notice] [pid 31030] AH00094: Command line: '/usr/sbin/apache2'

For the PHP-FPM,

Are the logs activated by default in the appliance?

Thanks!

**Comment by enoch85** [comment] 2019-01-25 15:07
Hmm, no error. 

PHP was added after version 13. But you can check if `service php7.2-fpm restart` works.

Does a reboot help?

**Comment by enoch85** [comment] 2019-01-25 15:08
And yeah, it shouldn't even work from 13 --> 15 as that's two major versions. So something is wrong here...

**Comment by enoch85** [comment] 2019-01-25 15:14
How is RAM usage and CPU?

Please show the output of `htop`

**Comment by Shoghi74** [comment] 2019-01-25 15:17
php7.2-fpm installed and server reboot. No change...

<img width="684" alt="htop nexcloud" src="https://user-images.githubusercontent.com/40488389/51754479-b4286f00-20bc-11e9-9002-72a1f23cc94d.PNG">

**Comment by Shoghi74** [comment] 2019-01-25 15:39
The log of php7.2-fpm:

[25-Jan-2019 16:12:06] NOTICE: fpm is running, pid 5028
[25-Jan-2019 16:12:06] NOTICE: ready to handle connections
[25-Jan-2019 16:12:06] NOTICE: systemd monitor interval set to 10000ms
[25-Jan-2019 16:12:54] NOTICE: Terminating ...
[25-Jan-2019 16:12:54] NOTICE: exiting, bye-bye!
[25-Jan-2019 16:14:09] NOTICE: fpm is running, pid 1712
[25-Jan-2019 16:14:09] NOTICE: ready to handle connections
[25-Jan-2019 16:14:09] NOTICE: systemd monitor interval set to 10000ms

**Comment by Shoghi74** [comment] 2019-01-25 16:22
Can we do a update revert?

**Comment by enoch85** [comment] 2019-01-25 19:18
@Shoghi74 There is a backup of the config files in `/mnt/NCBACKUP`, so you could revert with that. The data is in `/mnt/ncdata` so you can export that as well. 

I'd still would like to know what's going in here. 

Do you have Teamviewer? Please send me an email on the email address in my profile here on github so that I can have a look.

**Comment by Shoghi74** [comment] 2019-01-25 19:35
@enoch85,

Just sent you an email with teamviewer access.

Thanks.

Regards,

Shoghi

**Comment by enoch85** [comment] 2019-01-25 20:48
Steps to reproduce:

1. Run the Nextcloud VM
2, Try to update
3, Notice that you can't go from 13 --> 15
4. Install the snap so that the Nextcloud VM scripts think it's version 14
5. Run the update.sh script from the VM
6. Break your Nextcloud installation.

Closing as invalid since there is nothing wrong with the scripts.

**Closed by enoch85** 2019-01-25 20:48 UTC
