### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException

### ISSUE THREAD

**Issue by fgrosswig** [nextcloud/vm#552] opened 2018-05-23 09:26 UTC
Any clue about this error in here?

> Nextcloud 13.0.2

> Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing 'SELECT "fileid", "storage", "path", "parent", "name", "mimetype", "mimepart", "size", "mtime", "storage_mtime", "encrypted", "etag", "permissions", "checksum" FROM "oc_filecache" "file" WHERE ("storage" = ?) AND ((("mimepart" = ?) OR ("mimepart" = ?)) AND ("mtime" >= ?))' with params [4, 5, 3, -62104230392]: SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "-62104230392" is out of range for type integer
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 855: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "fileid"...', Array)
/var/www/nextcloud/lib/private/DB/Connection.php - line 195: Doctrine\DBAL\Connection->executeQuery('SELECT "fileid"...', Array, Array, NULL)
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 206: OC\DB\Connection->executeQuery('SELECT "fileid"...', Array, Array)
/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214: Doctrine\DBAL\Query\QueryBuilder->execute()
/var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 697: OC\DB\QueryBuilder\QueryBuilder->execute()
[internal function] OC\Files\Cache\Cache->searchQuery(Object(OC\Files\Search\SearchQuery))
/var/www/nextcloud/lib/private/Files/Node/Folder.php - line 245: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/Files/Node/Folder.php - line 201: OC\Files\Node\Folder->searchCommon('searchQuery', Array)
/var/www/nextcloud/apps/dav/lib/Files/FileSearchBackend.php - line 158: OC\Files\Node\Folder->search(Object(OC\Files\Search\SearchQuery))
/var/www/nextcloud/3rdparty/icewind/searchdav/src/DAV/SearchHandler.php - line 75: OCA\DAV\Files\FileSearchBackend->search(Object(SearchDAV\XML\BasicSearch))
/var/www/nextcloud/3rdparty/icewind/searchdav/src/DAV/SearchPlugin.php - line 123: SearchDAV\DAV\SearchHandler->handleSearchRequest(Array, Object(Sabre\HTTP\Response))
[internal function] SearchDAV\DAV\SearchPlugin->searchHandler(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method SEARCH', Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...')
{main}

**Comment by enoch85** [comment] 2018-05-23 10:20
@fgrosswig Thanks for reporting. No I don't know, there are several similar tickets in the nextcloud/server repo. Please use the search function.

So before you report any issues (questions and help are for the forum help.nextcloud.com) *please* use Google first and try to find the cauase yourself. If you find the cause to be an error in the VM then you are very welcome to report it. :)

This specific error I don't think anything to do with the VM as the PostgreSQL DB is all default --> closing.

**Closed by enoch85** 2018-05-23 10:20 UTC
