### ISSUE TITLE
deSEC DNS Renewal and TLS Registration Failing

### ISSUE THREAD

**Issue by antieon** [nextcloud/vm#2240] opened 2022-02-18 19:37 UTC
### Steps To Reproduce

Brand new installation of 2TB Hansson VM, when the registration of DNS-Renewals begins it comes up and says - sed: can't read /var/scripts/deSEC/.dedynauth: No such file or directory"

### Expected Result

The installation of DNS-Renewals and TLS registration completes.

### Actual Result

Installation of deSEC and activation of TLS fails

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/36601898/154748166-ed857ed4-97af-4fe7-ab54-403b5eb77679.png)

### Additional Context

Brand new install from VM, everything default minus Static IP

### Build Version

23.02

### Environment

By downloading the VM

### Environment Details

VMWare ESXi 7.0.2 U2.  Modified CPU & RAM configuration (4 x vCPU / 16GB RAM / disks set to Thick Provisioned vs Thin Provisioned)  - Configured with Static IP address

**Comment by antieon** [comment] 2022-02-18 20:00
Ran through the install again, leaving everything absolutely default (same VM CPU/memory/thin provisioned/DHCP IP) - and still fails at the same part with deSEC.
![image](https://user-images.githubusercontent.com/36601898/154753235-35b49abd-0aac-43fe-af07-29e038d98da9.png)

**Comment by enoch85** [comment] 2022-02-18 20:18
Some more relevant output:

```
Configuring ddclient
--------------------

Empty host list

The list of host names managed under your account is empty when retrieved 
from the dynamic DNS service website.

You may have provided an incorrect username or password, or the online 
account may have no host names configured.

Please check your account to be sure you have host names configured, then 
run "dpkg-reconfigure ddclient" to input your username and password again.

Setting up perl-openssl-defaults:amd64 (4) ...
Setting up libidn11:amd64 (1.33-2.2ubuntu2) ...
Setting up libnet-libidn-perl (0.12.ds-3build2) ...
Setting up libnet-ssleay-perl (1.88-2ubuntu1) ...
Setting up libio-socket-ssl-perl (2.067-1) ...
Processing triggers for systemd (245.4-4ubuntu3.15) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
CONNECT:  api.ipify.org
CONNECTED:  using SSL
SENDING:  GET / HTTP/1.0
SENDING:   Host: api.ipify.org
SENDING:   User-Agent: ddclient/3.8.3
SENDING:   Connection: close
SENDING:   
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: Cowboy
RECEIVE:  Connection: close
RECEIVE:  Content-Type: text/plain
RECEIVE:  Vary: Origin
RECEIVE:  Date: Fri, 18 Feb 2022 20:13:38 GMT
RECEIVE:  Content-Length: 13
RECEIVE:  Via: 1.1 vegur
RECEIVE:  
RECEIVE:  123.123.123.123
INFO:     forcing updating hanssonit.dedyn.io because no cached entry exists.
INFO:     setting IP address to 90.231.57.129 for hanssonit.dedyn.io
UPDATE:   updating hanssonit.dedyn.io
CONNECT:  update.dedyn.io
CONNECTED:  using SSL
SENDING:  GET /nic/update?system=dyndns&hostname=hanssonit.dedyn.io&myip=90.231.57.129 HTTP/1.0
SENDING:   Host: update.dedyn.io
SENDING:   Authorization: Basic *************************BQRVotTW9PTjA=
SENDING:   User-Agent: ddclient/3.8.3
SENDING:   Connection: close
SENDING:   
RECEIVE:  HTTP/1.1 401 Unauthorized
RECEIVE:  Server: nginx
RECEIVE:  Date: Fri, 18 Feb 2022 20:13:39 GMT
RECEIVE:  Content-Type: text/plain
RECEIVE:  Content-Length: 7
RECEIVE:  Connection: close
RECEIVE:  WWW-Authenticate: Token
RECEIVE:  Allow: GET, HEAD, OPTIONS
RECEIVE:  Vary: Origin
RECEIVE:  Strict-Transport-Security: max-age=31536000
RECEIVE:  
RECEIVE:  badauth
FAILED:   updating hanssonit.dedyn.io: authorization failed (HTTP/1.1 401 Unauthorized
FAILED:    Server: nginx
FAILED:    Date: Fri, 18 Feb 2022 20:13:39 GMT
FAILED:    Content-Type: text/plain
FAILED:    Content-Length: 7
FAILED:    Connection: close
FAILED:    WWW-Authenticate: Token
FAILED:    Allow: GET, HEAD, OPTIONS
FAILED:    Vary: Origin
FAILED:    Strict-Transport-Security: max-age=31536000
FAILED:    
FAILED:    badauth)
```

**Comment by enoch85** [comment] 2022-02-18 22:12
OK, so just found out that @peterthomassen archived the repo that we fetch the dedynauthfile from. That was unfortunate!

This is the new implementation: https://pypi.org/project/certbot-dns-desec/

**Comment by nils-wisiol** [comment] 2022-02-19 10:51
The issue wasn't caused by archiving the repository. The issue was caused by nextcloud/vm expecting the HEAD of master branch of desec-io/desec-certbot-hook [*] to include `hook.sh` and `.dedynauth` files, but [these files were removed](https://github.com/desec-io/desec-certbot-hook/commit/0bbc8cd63b372f7975938b4d825f8b4818fe2a0e). To provide a quick fix for this issue, I've restored `.dedynauth` at the master HEAD. Please confirm that this resolves the issue.

Please consider upgrading to desec-io/certbot-dns-desec, which follows a proper versioning scheme when installed via pip. Also, please do not rely on master/main branches never having incompatible changes. (E.g., by downloading files from a specific branch or commit id.)

[*] There is no master branch in desec-io/desec-certbot-hook for a while now, but githubusercontent.com silently saved the day by delivering content from the main branch instead.

**Comment by enoch85** [comment] 2022-02-19 11:05
@nils-wisiol Thanks for the quick response, but I'm sorry to say that doesn't fix the issue. I still get `badauth`. Haven't had time to look into it yet though.

Using your Certbot implementation would mean that we would have one implementation for deSEC and one for everything else. We could use Certbot if your implementation was more generic. Right now that doesn't seem to be the case. Please correct me if I'm wrong.

You have our implementation here [here](https://github.com/nextcloud/vm/blob/master/lib.sh#L769-L890) and [here](https://github.com/nextcloud/vm/blob/master/addons/desec.sh)

**Comment by nils-wisiol** [comment] 2022-02-19 11:44
I'm happy to investigate further, could you provide some more details? In the screenshot by the OP it says, ".dedynauth" could not be found. Does this error persist after my changes?

**Comment by enoch85** [comment] 2022-02-19 13:23
@nils-wisiol You could run the (linked) desec script yourself as a first step. It's not bound to just Nextcloud and this VM.

I'm currently on the road and can't do anything right now.

**Comment by enoch85** [comment] 2022-02-19 16:31
@nils-wisiol Working on a fix now to become independent of your old repo.

It would be super nice of you if you could start a PR where you replace the existing function with the certbot from you, using the same functions in our repo as much as possible.

**Comment by antieon** [comment] 2022-02-19 17:04
The installation progresses further, but it is trying to look to dedyn.io and not desec.io for the DDNS.  Is there a way to specify to go to deSEC.io vs dedyn.io?

![image](https://user-images.githubusercontent.com/36601898/154810961-f54bac4a-7730-476f-b479-9925fc5e8f9d.png)

**Comment by enoch85** [comment] 2022-02-19 17:10
@antieon I'm working on a fix now, I still don't know if anything changed in their API. I have just removed my account, and will do a 100% clean install just to be sure.

Right now the issue seems to be that the domain isn't registered with deSEC, and therefore DDclient fails.

**Comment by enoch85** [comment] 2022-02-19 18:30
@antieon Please try again.

**Closed** 2022-02-19 18:30 UTC
Labels: bug, Priority-1

**Comment by antieon** [comment] 2022-02-19 18:41
![image](https://user-images.githubusercontent.com/36601898/154814491-3f6c801e-fad0-4d15-9d85-7d40da7d2465.png)

**Comment by enoch85** [comment] 2022-02-19 18:51
Give it some time, Github needs to propagate the files.

Please try again.

**Comment by enoch85** [comment] 2022-02-19 19:20
@nils-wisiol You can delete the stuff again, we don't depend on your branch anymore.

Thanks!

**Comment by antieon** [comment] 2022-02-19 20:09
not working.

![image](https://user-images.githubusercontent.com/36601898/154817340-4a5a8c33-54af-48e9-bf3c-3836e500107e.png)

and then when I manually start the server_configuration.sh script again, still comes up and gives me the error from above as well.  And github is clearly reachable and the IP settings are correct - even configured the static IP again as well.

**Comment by antieon** [comment] 2022-02-19 20:11
![image](https://user-images.githubusercontent.com/36601898/154817422-d932c283-f98b-40bb-a932-370ced7aac13.png)

**Comment by antieon** [comment] 2022-02-19 20:39
deleted VM, started over... did not get the github connection issues - but still getting this error.

![image](https://user-images.githubusercontent.com/36601898/154818258-2272976d-829d-48d0-9934-d9cfa25fff3a.png)

**Comment by enoch85** [comment] 2022-02-19 22:06
@antieon 

1. Delete the VM
2. Import it again
3. Start the script
4. Post your result

Thanks!

Ref https://github.com/nextcloud/vm/commit/92eba8cc1a234cdda4c9128f00403c435ce7bc0a

**Comment by antieon** [comment] 2022-02-19 22:47
I have done that between every test thus far.

![image](https://user-images.githubusercontent.com/36601898/154821638-1a6a0fbb-89bd-454b-afcc-c9aba470c48a.png)

![image](https://user-images.githubusercontent.com/36601898/154821646-52a3fe79-4bcb-4c90-9220-9a873ca8bb9f.png)

![image](https://user-images.githubusercontent.com/36601898/154821661-f8820836-1b9a-4e6e-9dc4-7cbeb5231720.png)

**Comment by enoch85** [comment] 2022-02-20 08:03
Send me an email please, you'll get the latest version: https://github.com/nextcloud/vm/issues/2163

**Comment by antieon** [comment] 2022-02-20 16:47
Not finalized on the install yet, but this is a lot more promising than it has been.

![image](https://user-images.githubusercontent.com/36601898/154853875-0b26b70e-d6ee-4816-8ac6-ac59eefb42bb.png)

![image](https://user-images.githubusercontent.com/36601898/154853882-0fce12d0-5970-493e-ba9b-f55a2a41e1a7.png)

**Comment by antieon** [comment] 2022-02-20 18:01
Success confirmed, it is setup and I have had an external user connect to test it for me.  Thank you!

**Comment by enoch85** [comment] 2022-02-20 18:02
Thanks for reporting and helping out testing!
