### ISSUE TITLE
upgrade Ubuntu 18.04

### ISSUE THREAD

**Issue by miche7** [nextcloud/vm#1308] opened 2020-07-03 17:09 UTC
Hello,

And first of all thank you for all the work done. Nextcloud works well, it's a pleasure to have this powerful tool.

I am writing to you to find out if it would be possible (risky or not) to switch Ubuntu from version 18.04 to version 19.04 or 20.04

Why do you say to me?

Well, because I wanted to install a newer version of smbclient, in order to have an inotify function

Thanking you,

Yours

**Comment by enoch85** [comment] 2020-07-04 00:06
Hi,

Thanks for posting your issue/question.

Please read this: https://www.techandme.se/ubuntu-20-04-and-our-vms/

Hope it helps!

**Comment by enoch85** [comment] 2020-07-04 23:21
Since this is support, and not a bug, I'm closing.

**Closed by enoch85** 2020-07-04 23:21 UTC
Labels: Support
