### ISSUE TITLE
Nextcloud updater, Check for write permissions.

### ISSUE THREAD

**Issue by tmsd2001** [nextcloud/vm#1140] opened 2020-03-03 16:05 UTC
The current version is 17.0.3.
Update to Nextcloud 18.0.1 available. (channel: "stable")

On every update, I see the "Check for write permissions." error, if I try to manual update.
If I wait a couple of days, the updates run automatical in the background, without error.

**Comment by szaimen** [comment] 2020-03-03 16:13
@enoch85 this is probably the issue with the web updater beeing not disabled...

**Comment by szaimen** [comment] 2020-03-03 16:14
@tmsd2001 you have to run sudo bash /var/scripts/update.sh to update to NC 18.0.1

**Comment by enoch85** [comment] 2020-03-03 17:23
@szaimen Yeah, maybe we should disable the web updater since we already are notifying on how updates should be made?

@tmsd2001 Did you sign up for the automatic updater during the first setup? If yes, you don't need to care about doing updates: 

> the updates run automatical in the background, without error.

**Comment by szaimen** [comment] 2020-03-03 18:11
> Yeah, maybe we should disable the web updater since we already are notifying on how updates should be made?

Yes, I would definitely do that, but the option is not yet implemented: https://github.com/nextcloud/server/issues/18585#issuecomment-572517694

Do we want to find another way? Or just wait until the option is implemented in the server?

**Comment by enoch85** [comment] 2020-03-03 19:01
No let's wait until it's in core.

**Comment by enoch85** [comment] 2020-03-03 20:41
@tmsd2001 Since this is not a bug, I'll close this issue.

We're aware of the situation, and the VM isn't designed to just update Nextcloud, the built in update script does so much more than just update the core stuff. 

--> Close.

**Closed by enoch85** 2020-03-03 20:41 UTC

**Comment by Domainvoid** [comment] 2023-03-25 10:36
This is because the webserver you run has no permission to write updates in the folder. In my case, this solved my problem:
```
1. sudo chown -R apache:apache /var/www/html/nextcloud
2. sudo chmod -R 750 /var/www/html/nextcloud
3. sudo -u apache php /var/www/html/nextcloud/updater/updater.phar
```

**Comment by enoch85** [comment] 2023-03-25 15:04
Thanks for your comment @Domainvoid but that's not how it works in the VM. Also `apache:apache` is wrong. 

You can find more info here: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE
