### ISSUE TITLE
Update.sh -> upgrade from 22.2.7 to 23.0.4 fails (update script calls 24.0 instead)

### ISSUE THREAD

**Issue by IdefixRC** [nextcloud/vm#2322] opened 2022-05-15 16:14 UTC
### Steps To Reproduce

1. launching update via menu.sh or update.sh
2. update starts, latest version is indicated as 23.0.4 but then script throws error that double upgrade to 24.0 is not possible

### Expected Result

Expected: upgrade to 23.0.4
Tested this with a fresh install from VM appliance and upgrade runs. Also here the script informs that an upgrade to 24.0 will be performed, however after log-in to web console -> settings, version is shown as 23.0.4 with no further updates available

### Actual Result

.

### Build Version

22.2.7

### Environment

By downloading the VM

**Comment by enoch85** [comment] 2022-05-15 17:57
It's by design.

update.sh will always get the latest version, and that's why we introduced 'minor' some time ago.

You can read more here: 

https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE

https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/#reviews

**Comment by IdefixRC** [comment] 2022-05-16 02:24
Thanks for the reply.
The issue is that even when updating 23.0.4 to v24 - based on the output of the updater, the version shown in the webgui remains on v23.0.4 and is not moved to v24

Hence the confusion whether an upgrade to v24 is performed or not. 
So wondering whether it really upgrades to v24 or whether there is an error with the upgrade script and 23.0.4 is the latest it will go to anyway. in case of my v22 which is now stuck unless I purchase the upgrade product or do a fresh reinstall this upgrade to v23 is the one I would like to execute and which is shown as latest upgrade available also in the webgui - not v24

Thanks

**Comment by enoch85** [comment] 2022-05-16 05:57
> After that it requests whether to run the script one more time to update to v24.
However halfway through the backup process, the server executes the shutdown command from earlier.

Hmm, yeah that's an issue. It only applies if you have Automatic Updates configured though. Will think of something. Thanks for pointing it out.

**Comment by IdefixRC** [comment] 2022-05-16 09:23
@enoch85, I will need to deploy another server to test this out as mine is in the meantime on v24 (disabled the automatic updates and upgraded it earlier. Currently, it is migrating all the files from the old server which I could not update anymore :-(

**Comment by enoch85** [comment] 2022-05-16 17:46
This is now fixed.

**Closed** 2022-05-16 17:46 UTC
Labels: Support
